import yaml, glob, re, os, sys, zipfile, collections, shutil
import xml.etree.ElementTree as ET
OUT = sys.argv[1]
shutil.rmtree(f'{OUT}/devices', ignore_errors=True); os.makedirs(f'{OUT}/devices')  # README.md is kept

def slug(s):
    s = (s or '').lower()
    for a, b in (('ä','ae'),('ö','oe'),('ü','ue'),('ß','ss'),('–','-')): s = s.replace(a, b)
    return re.sub(r'[^a-z0-9]+', '-', s).strip('-') or 'obj'
def q(v):  # TOML basic string
    return '"' + str(v).replace('\\', '\\\\').replace('"', '\\"') + '"'
BARE = re.compile(r'^[A-Za-z0-9_-]+$')
def key(k): return k if BARE.match(k) else q(k)
def addr_sort(a): return tuple(int(x) for x in re.split(r'[./]', a))
def inline(pairs): return '{ ' + ', '.join(f'{k} = {v}' for k, v in pairs if v is not None) + ' }'

# ---- vendor texts from the application XMLs bundled in the project file ----
texts, chan_numbers = {}, {}   # app -> {ref_id: (text, function)}, app -> {channel_id: number}
try:
    z = zipfile.ZipFile('home_test.knxproj')
    for n in z.namelist():
        m = re.search(r'M-\d{4}/(M-\d{4}_A-[0-9A-F-]+)\.xml$', n)
        if not m: continue
        app = m.group(1); root = ET.fromstring(z.read(n)); ns = root.tag.split('}')[0] + '}'
        co = {e.get('Id'): e for e in root.iter(ns + 'ComObject')}
        t = {}
        for r in root.iter(ns + 'ComObjectRef'):
            b = co.get(r.get('RefId'))
            t[r.get('Id')] = (r.get('Text') or (b.get('Text') if b is not None else None),
                              r.get('FunctionText') or (b.get('FunctionText') if b is not None else None))
        texts[app] = t
        chan_numbers[app] = {c.get('Id'): c.get('Number') for c in root.iter(ns + 'Channel')}
except FileNotFoundError:
    pass
def norm_ref(ref): return re.sub(r'^(MD-\d+)_M-\d+_MI-\d+_', r'\1_', ref or '')
MI = re.compile(r'^(MD-\d+_M-\d+_MI-\d+)_')
def mi_of(s):
    m = MI.match(s or ''); return m.group(1) if m else None

# ---- load ----
g = yaml.safe_load(open('knx/groups.yaml'))
links = yaml.safe_load(open('knx/links.yaml'))['links']
devices = sorted((yaml.safe_load(open(f)) for f in glob.glob('knx/devices/*.yaml')), key=lambda d: addr_sort(d['address']))
conn = yaml.safe_load(open('knx/bussard.yaml'))

# ---- bussard.toml ----
c = conn['connection']
lines = ['# bussard.toml: how bussard reaches the bus. Hand-editable.', '', '[connection]']
lines += [f'{k} = {q(v)}' for k, v in c.items()]
open(f'{OUT}/bussard.toml', 'w').write('\n'.join(lines) + '\n')

# ---- groups.toml ----
lines = ['# groups.toml: the group-address plan. Hand-editable; re-import merges by address.', '']
lines.append('ranges = [')
w = max(len(k) for k in g['ranges']) + 2
for r, v in g['ranges'].items():
    lines.append(f'  {{ address = {q(r) + ",":<{w+1}} name = {q(v["name"])} }},')
lines += [']', '', 'groups = [']
wn = max(len(v['name']) for v in g['groups'].values()) + 2
for a, v in g['groups'].items():
    rest = []
    if 'dpt' in v: rest.append(f'dpt = {q(v["dpt"])}')
    if v.get('protected'): rest.append('protected = true')
    if 'description' in v: rest.append(f'description = {q(v["description"])}')
    name = q(v['name']) + (',' if rest else '')
    lines.append(f'  {{ address = {q(a) + ",":<9} name = {name:<{wn+1}} ' + ', '.join(rest) + ' },' if rest else f'  {{ address = {q(a) + ",":<9} name = {q(v["name"])} }},')
lines.append(']')
open(f'{OUT}/groups.toml', 'w').write('\n'.join(lines) + '\n')

# ---- devices + lock ----
pkeys_all = []
lock = ['# This file is @generated by `bussard import`. Do not edit it by hand.',
        '# Vendor facts for every device: application program, channels, com-objects, parameter refs.',
        'version = 1', f'source = {q(g.get("imported_from", ""))}', '']
notes = collections.Counter()
for d in devices:
    addr = d['address']; prod = d.get('product') or {}; app = prod.get('application_ref')
    co = d.get('com_objects') or {}; chans = d.get('channels') or {}; bases = d.get('module_bases') or {}
    tx = texts.get(app, {})
    # channel numbers: ETS Number when the application XML is at hand, else the
    # ordinal of the channel within the device (module channels in module order,
    # then static channels in CH-id order), which is how ETS counts them.
    chan_ids = list(chans)
    def chan_order(cid):
        m = re.match(r'^MD-(\d+)_M-(\d+)_MI-(\d+)_CH-(\d+)', cid)
        if m: return (0,) + tuple(int(x) for x in m.groups())
        return (1, int(re.search(r'CH-(\d+)', cid).group(1)))
    numbers = {}
    known = chan_numbers.get(app, {})
    if chan_ids and all(known.get(f'{app}_{cid}') for cid in chan_ids):
        numbers = {cid: int(known[f'{app}_{cid}']) for cid in chan_ids}
    else:
        if chan_ids: notes['devices with channel numbers taken from channel order'] += 1
        numbers = {cid: i for i, cid in enumerate(sorted(chan_ids, key=chan_order), 1)}
    mi_to_chan = {mi_of(cid): cid for cid in chan_ids if mi_of(cid)}
    # object keys: shortest unique within channel (function, text+function, name, +number)
    by_chan = collections.defaultdict(list)
    for n, o in co.items(): by_chan[o.get('channel')].append(n)
    link_names = {l['object']: l.get('name') for l in links.get(addr, [])}
    okey, osrc = {}, {}
    for ch, nums in by_chan.items():
        cands = {}
        for n in nums:
            t, f = tx.get(f'{app}_{norm_ref(co[n].get("ref"))}', (None, None))
            opts = []
            if f: opts.append(slug(f))
            if t and f: opts.append(slug(f'{t} {f}'))
            if link_names.get(n): opts.append(slug(link_names[n]))
            cands[n] = opts
        for level in range(3):
            taken = collections.Counter(c[level] for c in cands.values() if len(c) > level)
            for n, c in cands.items():
                if n not in okey and len(c) > level and taken[c[level]] == 1: okey[n] = c[level]; osrc[n] = 'vendor' if level < 2 or not link_names.get(n) or c[level] != slug(link_names[n]) else 'ets-name'
        for n, c in cands.items():
            if n not in okey:
                okey[n] = f'{c[-1]}-{n}' if c else None
                if c: notes['object keys disambiguated with the number'] += 1
    # parameters: slug unique within scope (channel or device), else slug@R-<r>
    pscope = collections.defaultdict(list)
    for k, v in (d.get('parameters') or {}).items():
        s, ref = k.split('@', 1); mi = mi_of(ref)
        r = re.search(r'_R-(\d+)$', ref).group(1)
        pscope[mi_to_chan.get(mi) if mi else None].append((s, ref, r, v, mi))
    pkeys = {}
    for scope, items in pscope.items():
        cnt = collections.Counter(s for s, *_ in items)
        for s, ref, r, v, mi in items:
            # escape hatch: R-<r> is unique per application; a module parameter
            # whose instance has no channel needs the full ref to stay unique.
            pkeys[ref] = s if cnt[s] == 1 and (scope or not mi) else (f'{s}@R-{r}' if not mi else f'{s}@{ref}')
    pkeys_all += list(pkeys.values())
    # ---- user file ----
    u = [f'# {addr}: {d["name"]}. Hand-editable in full; vendor facts live in bussard.lock.', '',
         f'address = {q(addr)}', f'name = {q(d["name"])}']
    if d.get('description'): u.append(f'description = {q(d["description"])}')
    if prod.get('order_number'): u.append(f'product = {q(prod["order_number"])}')
    if not prod.get('order_number') and app: u.append(f'application = {q(app)}')
    if d.get('location'):
        u += ['', '[location]'] + [f'{k} = {q(v)}' for k, v in d['location'].items()]
    if d.get('security'):
        u += ['', '[security]'] + [f'{k} = {str(v).lower() if isinstance(v, bool) else q(v)}' for k, v in d['security'].items()]
    dev_params = [(pkeys[ref], v) for s, ref, r, v, mi in pscope.get(None, [])]
    if dev_params:
        u += ['', '[parameters]'] + [f'{key(k)} = {q(v)}' for k, v in sorted(dev_params)]
    def link_lines(nums):
        out = []
        for l in sorted(links.get(addr, []), key=lambda l: l['object']):
            if l['object'] not in nums: continue
            k = key(okey.get(l['object']) or str(l['object']))
            if l.get('send'): out.append(f'{k}.send = {q(l["send"])}')
            if l.get('listen'): out.append(f'{k}.listen = [' + ', '.join(q(x) for x in l['listen']) + ']')
        return out
    top_links = link_lines({n for n, o in co.items() if not o.get('channel')} | {l['object'] for l in links.get(addr, []) if l['object'] not in co})
    if top_links: u += ['', '[links]'] + top_links
    for cid in sorted(chan_ids, key=lambda c: numbers[c]):
        body = [f'{key(pkeys[ref])} = {q(v)}' for s, ref, r, v, mi in sorted(pscope.get(cid, []))]
        body += link_lines({n for n, o in co.items() if o.get('channel') == cid})
        if not body: continue
        u += ['', f'[channel.{numbers[cid]}]  # {chans[cid]["name"]}'] + body
    open(f'{OUT}/devices/{addr}.toml', 'w').write('\n'.join(u) + '\n')
    # ---- lock entry ----
    L = ['[[device]]', f'address = {q(addr)}']
    for k, lk in (('order_number', 'product'), ('application_ref', 'application'), ('manufacturer', 'manufacturer'), ('manufacturer_ref', 'manufacturer_ref'), ('mask', 'mask')):
        if prod.get(k): L.append(f'{lk} = {q(prod[k])}')
    if chan_ids:
        L.append('channels = [')
        for cid in sorted(chan_ids, key=lambda c: numbers[c]):
            base = bases.get(mi_of(cid)) if mi_of(cid) else None
            L.append('  ' + inline([('number', numbers[cid]), ('id', q(cid)), ('text', q(chans[cid]['name'])), ('base', base)]) + ',')
        L.append(']')
    orphan = {k: v for k, v in bases.items() if k not in mi_to_chan}
    if orphan: L.append('module_bases = ' + inline([(key(k), v) for k, v in orphan.items()]))
    if co:
        L.append('objects = [')
        for n in sorted(co):
            o = co[n]; t, f = tx.get(f'{app}_{norm_ref(o.get("ref"))}', (None, None))
            ch = o.get('channel')
            L.append('  ' + inline([('number', n), ('channel', numbers.get(ch) if ch else None), ('key', q(okey[n]) if okey.get(n) else None),
                                    ('text', q(t) if t else None), ('function', q(f) if f else None), ('name', q(link_names[n]) if link_names.get(n) and not t else None),
                                    ('dpt', q(o['dpt']) if o.get('dpt') else None), ('size', q(o['size']) if o.get('size') else None),
                                    ('flags', q(o['flags'])), ('ref', q(o['ref']) if o.get('ref') else None)]) + ',')
        L.append(']')
    prefs = [(numbers.get(scope) if scope else None, pkeys[ref], ref) for scope, items in pscope.items() for s, ref, r, v, mi in items]
    if prefs:
        L.append('parameters = [')
        for ch, k, ref in sorted(prefs, key=lambda x: (x[0] or 0, x[1])):
            L.append('  ' + inline([('channel', ch), ('key', q(k)), ('ref', q(ref))]) + ',')
        L.append(']')
    lock += L + ['']
open(f'{OUT}/bussard.lock', 'w').write('\n'.join(lock))
open(f'{OUT}/.gitattributes', 'w').write('bussard.lock linguist-generated=true\n')
esc=sum(1 for v in pkeys_all if '@R-' in v); print('parameter keys:', len(pkeys_all), 'escaped:', esc); print('devices:', len(devices), '| notes:', dict(notes), '| apps with vendor texts:', sum(1 for d in devices if (d.get("product") or {}).get("application_ref") in texts))
