# 1.1.33: Präsenzmelder Mini Universal. Hand-editable in full; vendor facts live in bussard.lock.

address = "1.1.33"
name = "Präsenzmelder Mini Universal"
description = "Essen EG"
product = "3361-1MWW"

[location]
floor = "EG"
room = "Essen"

[parameters]
telegramm-nachtriggerung-a1 = "1"
