//! Device facts: what bussard read off a device that does not change while the
//! device keeps its firmware and application (issue #209).
//!
//! A describe of a KNX Data Secure device used to take 21-28 s because it
//! rediscovered the interface objects and every property description on every
//! run, and `reconstruct` / `apply` / the flash pre-flight walked the object
//! table again each time. The facts are stored once per device and reused while
//! a cheap identity read (the mask and the application id) still matches.
//!
//! # Where they live
//!
//! One generated TOML file per device, `<dir>/.bussard/facts/<ia>.toml`, next to the
//! history (`.bussard/history`), not in `devices/*.toml` or `bussard.lock`:
//!
//! - an ETS re-import rewrites `devices/*.toml` and `bussard.lock` and never
//!   touches `.bussard/`,
//!   so the facts survive it unchanged, and they are keyed on what the device
//!   itself reports (mask, application id), so a re-import that changes the
//!   application does not need to know about them: the next bus command sees
//!   the new application id and reads the facts again;
//! - the reviewed model files stay free of machine-observed data, so a `git
//!   diff` of `knx/` shows intent only (`bussard init` already excludes
//!   `.bussard/` from the repository), and `bussard.lock` stays what the model
//!   format says it is: written by `import` and `adopt` only, covered by
//!   snapshots and the model fingerprint, which a bus read must not change;
//! - the file is regenerated whole on every read, with a fixed field order, so
//!   two reads of the same device produce the same file apart from `read_at`.
//!
//! Deleting the file (or passing `--refresh-facts`) makes the next command read
//! everything again.

use std::path::{Path, PathBuf};
use std::time::SystemTime;

use serde::{Deserialize, Serialize};

use crate::IndividualAddress;

/// The facts directory under a model directory.
pub const FACTS_DIR: &str = ".bussard/facts";

/// The comment block written at the top of every facts file.
const HEADER: &str = "\
# This file is @generated by bussard from reads of the device (issue #209). Do not edit it by hand.
# Reused while the device reports the same mask and application id; delete
# this file or pass --refresh-facts to read the device again.
";

/// The on-disk document: a single `[device_facts]` table.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FactsFile {
    /// The facts.
    pub device_facts: DeviceFactsRecord,
}

/// Everything bussard caches about one device.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeviceFactsRecord {
    /// The device's individual address.
    pub address: IndividualAddress,
    /// When the facts were read, RFC 3339 UTC (`2026-09-25T10:11:12Z`).
    pub read_at: String,
    /// The mask version from the device descriptor, four hex digits (`07B0`).
    pub mask: String,
    /// The index of the application-program object whose `PID_PROGRAM_VERSION`
    /// is the application id, or `None` when the device has none.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub application_object: Option<u8>,
    /// The application id (`PID_PROGRAM_VERSION` of
    /// [`application_object`](Self::application_object)) the facts were read
    /// under, as hex (`00FA25001A`). `None` when there is no application object
    /// or it did not answer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub application_id: Option<String>,
    /// `PID_MAX_APDU_LENGTH` of the device object, when readable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_apdu: Option<u16>,
    /// How the device answered `A_Authorize_Request` with the free-access key,
    /// when a command presented it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub authorize: Option<AuthorizeVerdict>,
    /// How the object table was read.
    pub object_table_source: ObjectTableSource,
    /// The interface objects in index order.
    pub objects: Vec<ObjectFacts>,
}

/// How a device answered `A_Authorize_Request`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AuthorizeVerdict {
    /// Answered with level 0.
    Granted,
    /// Answered with a non-zero level.
    Denied,
    /// Did not answer, or answered with another service.
    Unsupported,
}

/// Which read produced the object table.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ObjectTableSource {
    /// `PID_IO_LIST` (device object, PID 71), read in a few multi-element reads.
    IoList,
    /// `PID_OBJECT_TYPE` probed one object index at a time.
    Walk,
}

/// One interface object.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ObjectFacts {
    /// The object index.
    pub index: u8,
    /// The interface-object type (`PID_OBJECT_TYPE`).
    pub object_type: u16,
    /// The property descriptions in index order, when they were walked
    /// (`describe`). `None` when only the object table was read.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub properties: Option<Vec<PropertyFacts>>,
}

/// One `A_PropertyDescription_Response`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PropertyFacts {
    /// The property index (1-based).
    pub index: u8,
    /// The property id.
    pub pid: u8,
    /// The property data type code.
    pub pdt: u8,
    /// Whether the property is writable.
    pub writable: bool,
    /// The maximum number of elements.
    pub max_elements: u16,
    /// The read access level.
    pub read_level: u8,
    /// The write access level.
    pub write_level: u8,
}

impl DeviceFactsRecord {
    /// The mask as a number, when [`mask`](Self::mask) parses.
    pub fn mask_value(&self) -> Option<u16> {
        u16::from_str_radix(self.mask.trim(), 16).ok()
    }

    /// The object table as `(index, object type)` pairs.
    pub fn object_table(&self) -> Vec<(u8, u16)> {
        self.objects
            .iter()
            .map(|o| (o.index, o.object_type))
            .collect()
    }

    /// Whether every object carries its property descriptions.
    pub fn has_properties(&self) -> bool {
        !self.objects.is_empty() && self.objects.iter().all(|o| o.properties.is_some())
    }
}

/// Formats a mask for [`DeviceFactsRecord::mask`].
pub fn format_mask(mask: u16) -> String {
    format!("{mask:04X}")
}

/// Formats an application id for [`DeviceFactsRecord::application_id`].
pub fn format_application_id(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02X}")).collect()
}

/// The current time as [`DeviceFactsRecord::read_at`] spells it.
pub fn now_stamp() -> String {
    crate::history::rfc3339(SystemTime::now())
}

/// Why facts could not be read or written.
#[derive(Debug, thiserror::Error)]
pub enum FactsError {
    /// The file could not be read or written.
    #[error("{}: {source}", path.display())]
    Io {
        /// The file.
        path: PathBuf,
        /// The I/O error.
        #[source]
        source: std::io::Error,
    },
    /// The file is not a valid facts document.
    #[error("{}: {message}", path.display())]
    Parse {
        /// The file.
        path: PathBuf,
        /// What was wrong.
        message: String,
    },
    /// The record could not be serialised.
    #[error("serialising the facts for {address}: {message}")]
    Serialize {
        /// The device.
        address: IndividualAddress,
        /// What went wrong.
        message: String,
    },
}

/// The facts file of `address` under the model directory `dir`.
pub fn facts_path(dir: &Path, address: IndividualAddress) -> PathBuf {
    dir.join(FACTS_DIR).join(format!("{address}.toml"))
}

/// Parses a facts document.
///
/// # Errors
///
/// [`FactsError::Parse`] for invalid TOML or an unknown field.
pub fn parse_facts(text: &str, path: &Path) -> Result<DeviceFactsRecord, FactsError> {
    let file: FactsFile = crate::toml_io::parse(path, text).map_err(|err| FactsError::Parse {
        path: path.to_path_buf(),
        message: err.to_string(),
    })?;
    Ok(file.device_facts)
}

/// Renders a facts document, header comment included.
///
/// # Errors
///
/// [`FactsError::Serialize`] when the record cannot be rendered.
pub fn render_facts(record: &DeviceFactsRecord) -> Result<String, FactsError> {
    let file = FactsFile {
        device_facts: record.clone(),
    };
    let body = toml::to_string(&file).map_err(|err| FactsError::Serialize {
        address: record.address,
        message: err.to_string(),
    })?;
    Ok(format!("{HEADER}{body}"))
}

/// Loads the facts of `address` from `dir`. `Ok(None)` when there is no file.
///
/// # Errors
///
/// [`FactsError`] for an unreadable or invalid file. A caller treats that as
/// "no facts" (they are a cache) and says so.
pub fn load_facts(
    dir: &Path,
    address: IndividualAddress,
) -> Result<Option<DeviceFactsRecord>, FactsError> {
    let path = facts_path(dir, address);
    let text = match std::fs::read_to_string(&path) {
        Ok(text) => text,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(source) => return Err(FactsError::Io { path, source }),
    };
    let record = parse_facts(&text, &path)?;
    if record.address != address {
        return Err(FactsError::Parse {
            path,
            message: format!("the file describes {}, not {address}", record.address),
        });
    }
    Ok(Some(record))
}

/// Writes the facts of `record.address` under `dir`, replacing the file whole
/// (written to a temporary file first, then renamed).
///
/// # Errors
///
/// [`FactsError`] when the directory or file cannot be written.
pub fn save_facts(dir: &Path, record: &DeviceFactsRecord) -> Result<PathBuf, FactsError> {
    let path = facts_path(dir, record.address);
    let text = render_facts(record)?;
    let parent = dir.join(FACTS_DIR);
    std::fs::create_dir_all(&parent).map_err(|source| FactsError::Io {
        path: parent.clone(),
        source,
    })?;
    let tmp = parent.join(format!(".{}.toml.tmp", record.address));
    std::fs::write(&tmp, text).map_err(|source| FactsError::Io {
        path: tmp.clone(),
        source,
    })?;
    std::fs::rename(&tmp, &path).map_err(|source| FactsError::Io {
        path: path.clone(),
        source,
    })?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    type TestResult = Result<(), Box<dyn std::error::Error>>;

    fn record() -> Result<DeviceFactsRecord, Box<dyn std::error::Error>> {
        Ok(DeviceFactsRecord {
            address: "1.1.12".parse()?,
            read_at: "2026-09-25T10:11:12Z".to_string(),
            mask: format_mask(0x07B0),
            application_object: Some(3),
            application_id: Some(format_application_id(&[0x00, 0x04, 0xD1, 0x42, 0x21])),
            max_apdu: Some(233),
            authorize: Some(AuthorizeVerdict::Granted),
            object_table_source: ObjectTableSource::IoList,
            objects: vec![
                ObjectFacts {
                    index: 0,
                    object_type: 0,
                    properties: Some(vec![PropertyFacts {
                        index: 1,
                        pid: 1,
                        pdt: 0x04,
                        writable: false,
                        max_elements: 1,
                        read_level: 3,
                        write_level: 0,
                    }]),
                },
                ObjectFacts {
                    index: 1,
                    object_type: 1,
                    properties: None,
                },
            ],
        })
    }

    #[test]
    fn test_render_facts_round_trips() -> TestResult {
        let rec = record()?;
        let text = render_facts(&rec)?;
        assert!(text.starts_with("# This file is @generated by bussard"));
        assert!(text.contains("[device_facts]"));
        let back = parse_facts(&text, Path::new("x.toml"))?;
        assert_eq!(back, rec);
        assert_eq!(back.mask_value(), Some(0x07B0));
        assert_eq!(back.object_table(), vec![(0, 0), (1, 1)]);
        assert!(!back.has_properties());
        Ok(())
    }

    #[test]
    fn test_parse_facts_rejects_unknown_fields() -> TestResult {
        let text = render_facts(&record()?)?;
        let extra = text.replace("mask = \"07B0\"\n", "mask = \"07B0\"\ncolour = \"blue\"\n");
        assert_ne!(extra, text, "the fixture must contain the mask line");
        assert!(parse_facts(&extra, Path::new("x.toml")).is_err());
        let nested = text.replace("pid = 1\n", "pid = 1\nunit = \"none\"\n");
        assert_ne!(nested, text);
        assert!(parse_facts(&nested, Path::new("x.toml")).is_err());
        let top = format!("other = 1\n{text}");
        assert!(parse_facts(&top, Path::new("x.toml")).is_err());
        Ok(())
    }

    #[test]
    fn test_save_facts_then_load_facts() -> TestResult {
        let dir = std::env::temp_dir().join(format!("bussard-facts-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        let rec = record()?;
        assert!(load_facts(&dir, rec.address)?.is_none());
        let path = save_facts(&dir, &rec)?;
        assert_eq!(path, dir.join(".bussard/facts/1.1.12.toml"));
        assert_eq!(load_facts(&dir, rec.address)?, Some(rec.clone()));
        // A file for another device under this name is refused.
        assert!(load_facts(&dir, "1.1.13".parse()?)?.is_none());
        std::fs::copy(&path, facts_path(&dir, "1.1.13".parse()?))?;
        assert!(load_facts(&dir, "1.1.13".parse()?).is_err());
        std::fs::remove_dir_all(&dir)?;
        Ok(())
    }

    #[test]
    fn test_save_facts_survives_a_reimport_save() -> TestResult {
        // An ETS re-import saves the model with `save_pruning`, which rewrites
        // `devices/*.toml` and `bussard.lock` and prunes device files; the facts
        // under `.bussard/` must come through untouched.
        let dir =
            std::env::temp_dir().join(format!("bussard-facts-reimport-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(dir.join("devices"))?;
        for (ia, name) in [("1.1.12", "Button"), ("1.1.13", "Gone")] {
            std::fs::write(
                dir.join("devices").join(format!("{ia}.toml")),
                format!("address = \"{ia}\"\nname = \"{name}\"\n"),
            )?;
        }
        let rec = record()?;
        save_facts(&dir, &rec)?;
        let before = std::fs::read(facts_path(&dir, rec.address))?;
        let mut model = crate::Model::load(&dir)?;
        let gone: IndividualAddress = "1.1.13".parse()?;
        model.devices.remove(&gone);
        for device in model.devices.values_mut() {
            device.device.name = "Renamed button".to_string();
        }
        model.save_pruning(&dir)?;
        assert!(!dir.join("devices").join("1.1.13.toml").exists());
        assert!(
            std::fs::read_to_string(dir.join("devices").join("1.1.12.toml"))?.contains("Renamed")
        );
        assert_eq!(std::fs::read(facts_path(&dir, rec.address))?, before);
        assert_eq!(load_facts(&dir, rec.address)?, Some(rec));
        std::fs::remove_dir_all(&dir)?;
        Ok(())
    }
}
