//! The on-disk shapes of the model files and the join/split between a device
//! file, its `bussard.lock` entry and the in-memory [`Device`].
//!
//! See `docs/model-format.md` for the contract. In short: a device file holds
//! what the user means (name, location, parameter values, links) under keys
//! the lock assigns; the lock holds the vendor facts (product identity, channel
//! ids, the com-object table, the parameter refs). [`join_device`] rebuilds the
//! in-memory [`Device`] and its [`Link`]s from both; [`lock_entry`] and
//! [`device_entries`] split them again for a save.

use std::collections::{BTreeMap, BTreeSet};
use std::ops::Range;
use std::path::Path;

use serde::Deserialize;

use crate::address::{GroupAddress, IndividualAddress};
use crate::dpt::Dpt;
use crate::flags::Flags;
use crate::loader::LoadError;
use crate::param_model::{
    ParamDef, ProductModel, ProductModels, enum_code, enum_label, key_to_param_id,
};
use crate::schema::{
    Channel, ComObject, Device, DeviceLock, DeviceSecurity, Link, Location, LockedParameter,
    Product, Spelling,
};
use crate::toml_io::{self, ParseError};

/// The only `bussard.lock` format version this build reads and writes.
pub const LOCK_VERSION: u32 = 1;

/// The first line of every `bussard.lock`.
pub const LOCK_HEADER: &str = "# This file is @generated by `bussard import` and `bussard adopt`. \
Do not edit it by hand.";

// ---------------------------------------------------------------------------
// groups.toml
// ---------------------------------------------------------------------------

/// `groups.toml` as parsed.
#[derive(Debug, Deserialize, Default)]
#[serde(deny_unknown_fields)]
pub(crate) struct GroupsFile {
    pub project: Option<String>,
    #[serde(default)]
    pub ranges: Vec<RangeEntry>,
    #[serde(default)]
    pub groups: Vec<GroupEntry>,
}

/// One `ranges` entry.
#[derive(Debug, Deserialize, Clone, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub(crate) struct RangeEntry {
    pub address: String,
    pub name: String,
}

/// One `groups` entry.
#[derive(Debug, Deserialize, Clone, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub(crate) struct GroupEntry {
    pub address: GroupAddress,
    pub name: String,
    pub dpt: Option<Dpt>,
    pub description: Option<String>,
    #[serde(default)]
    pub protected: bool,
    #[serde(default)]
    pub secure: bool,
}

// ---------------------------------------------------------------------------
// bussard.lock
// ---------------------------------------------------------------------------

/// `bussard.lock` as parsed and as rendered.
#[derive(Debug, Deserialize, Clone, PartialEq, Eq, Default)]
#[serde(deny_unknown_fields)]
pub(crate) struct LockFile {
    pub version: u32,
    pub source: Option<String>,
    pub language: Option<String>,
    #[serde(default, rename = "device")]
    pub devices: Vec<LockDevice>,
}

/// One `[[device]]` entry of the lock.
#[derive(Debug, Deserialize, Clone, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub(crate) struct LockDevice {
    pub address: IndividualAddress,
    pub product: Option<String>,
    pub application: Option<String>,
    pub manufacturer: Option<String>,
    pub manufacturer_ref: Option<String>,
    pub hardware_ref: Option<String>,
    pub mask: Option<String>,
    #[serde(default)]
    pub secure_capable: bool,
    #[serde(default)]
    pub has_fdsk_certificate: bool,
    pub sequence_number: Option<u64>,
    #[serde(default)]
    pub channels: Vec<LockChannel>,
    #[serde(default)]
    pub module_bases: BTreeMap<String, u32>,
    #[serde(default)]
    pub objects: Vec<LockObject>,
    #[serde(default)]
    pub parameters: Vec<LockParameter>,
    #[serde(default)]
    pub hidden: Vec<LockHidden>,
}

/// One `hidden[]` entry: a value ETS stores for a parameter ref the
/// configuration does not show.
#[derive(Debug, Deserialize, Clone, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub(crate) struct LockHidden {
    #[serde(rename = "ref")]
    pub reference: String,
    pub value: String,
}

/// One `channels[]` entry.
#[derive(Debug, Deserialize, Clone, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub(crate) struct LockChannel {
    pub key: Option<String>,
    pub id: String,
    pub number: Option<u32>,
    pub text: Option<String>,
    pub label_ref: Option<String>,
    pub base: Option<u32>,
}

impl LockChannel {
    /// The handle the device file uses for this channel.
    pub fn handle(&self) -> &str {
        self.key.as_deref().unwrap_or(&self.id)
    }
}

/// One `objects[]` entry.
#[derive(Debug, Deserialize, Clone, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub(crate) struct LockObject {
    pub number: u16,
    pub key: Option<String>,
    pub channel: Option<String>,
    pub text: Option<String>,
    pub function: Option<String>,
    pub dpt: Option<Dpt>,
    pub size: Option<String>,
    pub flags: Flags,
    #[serde(rename = "ref")]
    pub reference: Option<String>,
    #[serde(default)]
    pub secure: bool,
}

/// One `parameters[]` entry.
#[derive(Debug, Deserialize, Clone, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub(crate) struct LockParameter {
    pub key: String,
    pub channel: Option<String>,
    #[serde(rename = "ref")]
    pub reference: String,
    pub param: Option<String>,
}

// ---------------------------------------------------------------------------
// devices/<address>.toml
// ---------------------------------------------------------------------------

/// The typed top level of a device file. The scope tables (`[parameters]`,
/// `[links]`, `[channel.*]`) are accepted as raw tables here and classified
/// from the span-carrying document by [`scope_entries`].
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct DeviceFileTop {
    pub address: IndividualAddress,
    pub name: String,
    pub description: Option<String>,
    pub product: Option<String>,
    pub application: Option<String>,
    pub replaced: Option<String>,
    pub location: Option<Location>,
    pub security: Option<SecurityIntent>,
    #[serde(default)]
    #[allow(dead_code)] // Classified from the document, see `scope_entries`.
    pub parameters: toml::Table,
    #[serde(default)]
    #[allow(dead_code)] // Classified from the document, see `scope_entries`.
    pub links: toml::Table,
    #[serde(default)]
    #[allow(dead_code)] // Classified from the document, see `scope_entries`.
    pub channel: BTreeMap<String, toml::Table>,
}

/// The `[security]` table of a device file: intent only.
#[derive(Debug, Deserialize, Clone, Copy, Default)]
#[serde(deny_unknown_fields)]
pub(crate) struct SecurityIntent {
    #[serde(default)]
    pub activated: bool,
    #[serde(default)]
    pub secure_commissioning: bool,
}

/// Which table of a device file an entry sits in.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum TableRef {
    /// `[parameters]`.
    Parameters,
    /// `[links]`.
    Links,
    /// `[channel.<handle>]`.
    Channel(String),
}

impl TableRef {
    /// The channel handle, for a channel table.
    pub fn scope(&self) -> Option<&str> {
        match self {
            TableRef::Channel(h) => Some(h),
            _ => None,
        }
    }

    /// The model-relative table path, for diagnostics.
    pub fn label(&self) -> String {
        match self {
            TableRef::Parameters => "[parameters]".to_string(),
            TableRef::Links => "[links]".to_string(),
            TableRef::Channel(h) => format!("[channel.{h}]"),
        }
    }
}

/// The value of one classified device-file entry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum EntryValue {
    /// A parameter value, in its string form.
    Param(String),
    /// A com-object entry.
    Object {
        send: Option<GroupAddress>,
        listen: Vec<GroupAddress>,
        name: Option<String>,
    },
}

/// One classified entry of a device file's scope tables.
#[derive(Debug, Clone)]
pub(crate) struct FileEntry {
    /// The table it sits in.
    pub table: TableRef,
    /// The parameter page, for an entry one level down.
    pub page: Option<String>,
    /// The key as written.
    pub key: String,
    /// The value.
    pub value: EntryValue,
    /// The key's span in the file, when known.
    pub span: Option<Range<usize>>,
}

impl FileEntry {
    /// The key as the lock spells it: `page.key` for a page entry.
    pub fn full_key(&self) -> String {
        match &self.page {
            Some(page) => format!("{page}.{}", self.key),
            None => self.key.clone(),
        }
    }
}

/// The classified contents of a device file's scope tables.
#[derive(Debug, Clone, Default)]
pub(crate) struct DeviceEntries {
    /// Every parameter and object entry, in file order.
    pub entries: Vec<FileEntry>,
    /// Each `[channel.<handle>]` table with its optional `name`, in file order.
    pub channels: Vec<(String, Option<String>, Option<Range<usize>>)>,
}

/// Classifies the scope tables of a parsed device file.
pub(crate) fn scope_entries(
    path: &Path,
    text: &str,
    doc: &toml_edit::Document<String>,
) -> Result<DeviceEntries, ParseError> {
    let mut out = DeviceEntries::default();
    let root = doc.as_table();
    for (name, table) in [
        ("parameters", TableRef::Parameters),
        ("links", TableRef::Links),
    ] {
        if let Some(t) = root.get(name).and_then(toml_edit::Item::as_table_like) {
            classify_table(path, text, t, &table, None, &mut out.entries)?;
        }
    }
    if let Some(channels) = root.get("channel").and_then(toml_edit::Item::as_table_like) {
        for (handle, item) in channels.iter() {
            let span = channels.get_key_value(handle).and_then(|(k, _)| k.span());
            let Some(t) = item.as_table_like() else {
                return Err(toml_io::error_at(
                    path,
                    text,
                    item.span().or(span),
                    &format!("invalid type: `channel.{handle}` must be a table"),
                ));
            };
            let name = match t.get("name") {
                None => None,
                Some(item) => match item.as_str() {
                    Some(s) => Some(s.to_string()),
                    None => {
                        return Err(toml_io::error_at(
                            path,
                            text,
                            item.span(),
                            &format!("invalid type: {}, expected a string", kind_of(item)),
                        ));
                    }
                },
            };
            out.channels.push((handle.to_string(), name, span));
            let table = TableRef::Channel(handle.to_string());
            classify_table(path, text, t, &table, None, &mut out.entries)?;
        }
    }
    Ok(out)
}

/// A serde-style description of an item's type, for error messages.
fn kind_of(item: &toml_edit::Item) -> String {
    match item {
        toml_edit::Item::None => "nothing".to_string(),
        toml_edit::Item::Table(_) => "table".to_string(),
        toml_edit::Item::ArrayOfTables(_) => "array of tables".to_string(),
        toml_edit::Item::Value(v) => match v {
            toml_edit::Value::String(s) => format!("string {:?}", s.value()),
            toml_edit::Value::Integer(i) => format!("integer `{}`", i.value()),
            toml_edit::Value::Float(f) => format!("floating point `{}`", f.value()),
            toml_edit::Value::Boolean(b) => format!("boolean `{}`", b.value()),
            toml_edit::Value::Datetime(d) => format!("datetime `{}`", d.value()),
            toml_edit::Value::Array(_) => "sequence".to_string(),
            toml_edit::Value::InlineTable(_) => "map".to_string(),
        },
    }
}

/// The keys an object entry may carry.
const OBJECT_FIELDS: [&str; 3] = ["send", "listen", "name"];

/// Classifies the entries of one scope table (or page).
fn classify_table(
    path: &Path,
    text: &str,
    table: &dyn toml_edit::TableLike,
    at: &TableRef,
    page: Option<&str>,
    out: &mut Vec<FileEntry>,
) -> Result<(), ParseError> {
    for (key, item) in table.iter() {
        if page.is_none() && matches!(at, TableRef::Channel(_)) && key == "name" {
            continue;
        }
        let key_span = table.get_key_value(key).and_then(|(k, _)| k.span());
        let err = |span: Option<Range<usize>>, message: String| {
            toml_io::error_at(path, text, span.or_else(|| key_span.clone()), &message)
        };
        if let Some(sub) = item.as_table_like() {
            let keys: Vec<&str> = sub.iter().map(|(k, _)| k).collect();
            let is_object = keys.iter().all(|k| OBJECT_FIELDS.contains(k))
                || keys.iter().any(|k| *k == "send" || *k == "listen");
            if is_object {
                let value = object_value(path, text, sub, key_span.clone())?;
                out.push(FileEntry {
                    table: at.clone(),
                    page: page.map(str::to_string),
                    key: key.to_string(),
                    value,
                    span: key_span,
                });
                continue;
            }
            if page.is_some() {
                return Err(err(
                    item.span(),
                    format!(
                        "invalid type: table `{key}` inside a parameter page; pages hold \
                         parameters one level down only"
                    ),
                ));
            }
            classify_table(path, text, sub, at, Some(key), out)?;
            continue;
        }
        let value = match item {
            toml_edit::Item::Value(toml_edit::Value::String(s)) => s.value().clone(),
            toml_edit::Item::Value(toml_edit::Value::Integer(i)) => i.value().to_string(),
            toml_edit::Item::Value(toml_edit::Value::Boolean(b)) => b.value().to_string(),
            toml_edit::Item::Value(toml_edit::Value::Float(_)) => {
                // Quote the float as written (`1.10`, not `1.1`).
                let source = item
                    .span()
                    .and_then(|s| text.get(s))
                    .map(|s| s.trim().to_string())
                    .unwrap_or_else(|| kind_of(item));
                return Err(err(
                    item.span(),
                    format!("invalid type: floating point `{source}`, expected a string"),
                ));
            }
            _ => {
                return Err(err(
                    item.span(),
                    format!(
                        "invalid type: {}, expected a string, integer or boolean (a parameter) \
                         or a table of `send`, `listen`, `name` (an object)",
                        kind_of(item)
                    ),
                ));
            }
        };
        out.push(FileEntry {
            table: at.clone(),
            page: page.map(str::to_string),
            key: key.to_string(),
            value: EntryValue::Param(value),
            span: key_span,
        });
    }
    Ok(())
}

/// Reads an object entry's `send` / `listen` / `name`.
fn object_value(
    path: &Path,
    text: &str,
    table: &dyn toml_edit::TableLike,
    key_span: Option<Range<usize>>,
) -> Result<EntryValue, ParseError> {
    let mut send = None;
    let mut listen = Vec::new();
    let mut name = None;
    for (field, item) in table.iter() {
        let span = item
            .span()
            .or_else(|| table.get_key_value(field).and_then(|(k, _)| k.span()))
            .or_else(|| key_span.clone());
        let err = |message: String| toml_io::error_at(path, text, span.clone(), &message);
        let ga = |item: &toml_edit::Item| -> Result<GroupAddress, ParseError> {
            let Some(s) = item.as_str() else {
                return Err(err(format!(
                    "invalid type: {}, expected a string",
                    kind_of(item)
                )));
            };
            s.parse::<GroupAddress>()
                .map_err(|e| err(format!("invalid group address {s:?}: {e}")))
        };
        match field {
            "send" => send = Some(ga(item)?),
            "listen" => {
                let Some(array) = item.as_array() else {
                    return Err(err(format!(
                        "invalid type: {}, expected a sequence",
                        kind_of(item)
                    )));
                };
                for value in array.iter() {
                    let span = value.span().or_else(|| span.clone());
                    let Some(s) = value.as_str() else {
                        return Err(toml_io::error_at(
                            path,
                            text,
                            span,
                            "invalid type: expected a group address string",
                        ));
                    };
                    listen.push(s.parse::<GroupAddress>().map_err(|e| {
                        toml_io::error_at(
                            path,
                            text,
                            span.clone(),
                            &format!("invalid group address {s:?}: {e}"),
                        )
                    })?);
                }
            }
            "name" => match item.as_str() {
                Some(s) => name = Some(s.to_string()),
                None => {
                    return Err(err(format!(
                        "invalid type: {}, expected a string",
                        kind_of(item)
                    )));
                }
            },
            other => {
                let span = table.get_key_value(other).and_then(|(k, _)| k.span());
                return Err(toml_io::error_at(
                    path,
                    text,
                    span,
                    &format!("unknown field `{other}`, expected one of `send`, `listen`, `name`"),
                ));
            }
        }
    }
    Ok(EntryValue::Object { send, listen, name })
}

// ---------------------------------------------------------------------------
// Resolution through the lock
// ---------------------------------------------------------------------------

/// Resolves device-file keys to object numbers and parameter refs through a
/// lock entry, and parameter keys the lock does not list through the
/// device's product model when one is loaded.
#[derive(Debug, Default)]
pub(crate) struct Resolver<'a> {
    /// `(scope, key)` → object number.
    objects: BTreeMap<(Option<String>, String), u16>,
    /// key → the object number when the key is unique within the device.
    objects_any: BTreeMap<String, Option<u16>>,
    /// `(scope, key)` → parameter ref.
    params: BTreeMap<(Option<String>, String), String>,
    /// key → the ref of a device-level parameter when the key is unique
    /// within the device, so it resolves from a channel table too. A channel
    /// parameter does not resolve from another table: the lock lists only
    /// stored parameters, so the same key in another channel is most likely
    /// that channel's own parameter (resolved through the product model).
    params_any: BTreeMap<String, Option<String>>,
    /// Every key per scope, for the E023 listing.
    keys: BTreeMap<Option<String>, BTreeSet<String>>,
    /// The product model of the device's application, for parameter keys
    /// the lock does not list.
    model: Option<&'a ProductModel>,
    /// Channel handle → the module-instance selector of the channel (`None`
    /// for an application channel).
    selectors: BTreeMap<String, Option<String>>,
}

impl<'a> Resolver<'a> {
    /// Builds the resolver for a lock entry (an empty one without) and the
    /// device's product model, through which a parameter key the lock does
    /// not list resolves.
    pub fn with_model(lock: Option<&LockDevice>, model: Option<&'a ProductModel>) -> Self {
        let mut r = Resolver {
            model,
            ..Resolver::default()
        };
        let Some(lock) = lock else {
            return r;
        };
        for ch in &lock.channels {
            r.selectors.insert(
                ch.handle().to_string(),
                channel_selector(&ch.id).map(str::to_string),
            );
        }
        for object in &lock.objects {
            let scope = object.channel.clone();
            let key = object
                .key
                .clone()
                .unwrap_or_else(|| object.number.to_string());
            r.keys.entry(scope.clone()).or_default().insert(key.clone());
            if let Some(k) = &object.key {
                r.objects.insert((scope, k.clone()), object.number);
                r.objects_any
                    .entry(k.clone())
                    .and_modify(|n| *n = None)
                    .or_insert(Some(object.number));
            }
        }
        for param in &lock.parameters {
            let scope = param.channel.clone();
            r.keys
                .entry(scope.clone())
                .or_default()
                .insert(param.key.clone());
            let device_level = scope.is_none();
            r.params
                .insert((scope, param.key.clone()), param.reference.clone());
            r.params_any
                .entry(param.key.clone())
                .and_modify(|p| *p = None)
                .or_insert(device_level.then(|| param.reference.clone()));
        }
        r
    }

    /// The object number `key` names in `scope`: a bare number, or a lock key
    /// (exact scope first, else unique within the device).
    pub fn object(&self, scope: Option<&str>, key: &str) -> Option<u16> {
        if let Ok(n) = key.parse::<u16>() {
            return Some(n);
        }
        self.objects
            .get(&(scope.map(str::to_string), key.to_string()))
            .copied()
            .or_else(|| self.objects_any.get(key).copied().flatten())
    }

    /// The parameter ref `key` names in `scope` through the lock, else
    /// through the product model.
    pub fn param_ref(&self, scope: Option<&str>, key: &str) -> Option<String> {
        self.locked_param_ref(scope, key)
            .map(str::to_string)
            .or_else(|| self.model_param_ref(scope, key))
    }

    /// The parameter ref `key` names in `scope` through the lock alone.
    pub fn locked_param_ref(&self, scope: Option<&str>, key: &str) -> Option<&str> {
        self.params
            .get(&(scope.map(str::to_string), key.to_string()))
            .map(String::as_str)
            .or_else(|| self.params_any.get(key).and_then(|r| r.as_deref()))
    }

    /// The parameter ref a key the lock does not list names in `scope`,
    /// through the product model ([`ProductModel::resolve_key`]). A scope
    /// the lock does not define resolves nothing.
    pub fn model_param_ref(&self, scope: Option<&str>, key: &str) -> Option<String> {
        let model = self.model?;
        if key.contains('@') {
            return None;
        }
        let selector = match scope {
            Some(handle) => self.selectors.get(handle)?.as_deref(),
            None => None,
        };
        model.resolve_key(selector, key)
    }

    /// The in-memory parameter key for a file key: `<slug>@<ref>` when the lock
    /// resolves it, else the key as written (the `<slug>@<ref>` escape hatch,
    /// or an unknown key that validation reports).
    pub fn param_mem_key(&self, scope: Option<&str>, key: &str) -> String {
        match self.param_ref(scope, key) {
            Some(reference) => param_mem_key(key, &reference),
            None => key.to_string(),
        }
    }

    /// Whether the lock knows `key` as a parameter in `scope` (or uniquely).
    pub fn knows_param(&self, scope: Option<&str>, key: &str) -> bool {
        self.param_ref(scope, key).is_some()
    }

    /// The keys the lock assigns in `scope`, sorted.
    pub fn keys_in(&self, scope: Option<&str>) -> Vec<String> {
        self.keys
            .get(&scope.map(str::to_string))
            .map(|k| k.iter().cloned().collect())
            .unwrap_or_default()
    }
}

/// The in-memory key (`<slug>@<ref>`, see [`Device::parameters`]) of the
/// parameter a device file names `file_key` and the lock resolves to
/// `reference`: the escape-hatch key itself when it already names that ref,
/// else the slug of the key (a page-qualified `sollwerte.komfort` becomes
/// `sollwerte-komfort`) joined to the ref.
///
/// The loader and the importer both key parameters this way, so a model built
/// by `import` equals the one a later load reads back.
pub fn param_mem_key(file_key: &str, reference: &str) -> String {
    match file_key.split_once('@') {
        Some((_, r)) if r == reference => file_key.to_string(),
        Some((head, _)) => format!("{}@{reference}", slug(head)),
        None => format!("{}@{reference}", slug(file_key)),
    }
}

/// The in-memory key of a channel's label parameter (the lock's
/// `label_ref`), whose value is the channel `name` in the device file.
pub fn label_mem_key(reference: &str) -> String {
    format!("label@{reference}")
}

/// The in-memory key of a value ETS stores for a parameter ref the
/// configuration does not show (the lock's `hidden[]`). It is kept with the
/// other values, so a flash writes it, but the device file does not show it.
pub fn hidden_mem_key(reference: &str) -> String {
    format!("{HIDDEN_PREFIX}{reference}")
}

/// The prefix of [`hidden_mem_key`].
const HIDDEN_PREFIX: &str = "hidden@";

/// Whether an in-memory parameter key is a [`hidden_mem_key`].
pub fn is_hidden_mem_key(key: &str) -> bool {
    key.starts_with(HIDDEN_PREFIX)
}

/// The contract's slug: lowercase, `ä ö ü ß` to `ae oe ue ss`, every run of
/// characters outside `[a-z0-9]` collapsed to `-`, trimmed; empty becomes `x`.
pub fn slug(text: &str) -> String {
    let mut out = String::new();
    let mut dash = false;
    for c in text.chars().flat_map(char::to_lowercase) {
        let mapped: &str = match c {
            'ä' => "ae",
            'ö' => "oe",
            'ü' => "ue",
            'ß' => "ss",
            _ => "",
        };
        if !mapped.is_empty() {
            out.push_str(mapped);
            dash = false;
        } else if c.is_ascii_lowercase() || c.is_ascii_digit() {
            out.push(c);
            dash = false;
        } else if !dash && !out.is_empty() {
            out.push('-');
            dash = true;
        }
    }
    let trimmed = out.trim_matches('-');
    if trimmed.is_empty() {
        "x".to_string()
    } else {
        trimmed.to_string()
    }
}

/// The module-instance selector (`MD-1_M-3_MI-1`) of a channel id
/// (`MD-1_M-3_MI-1_CH-80`), when the channel is a module instance.
pub(crate) fn channel_selector(id: &str) -> Option<&str> {
    let (selector, _) = id.rsplit_once("_CH-")?;
    (selector.starts_with("MD-") && selector.contains("_MI-")).then_some(selector)
}

/// The ref of an in-memory parameter key (`<slug>@<ref>`).
fn ref_of(mem_key: &str) -> Option<&str> {
    mem_key
        .split_once('@')
        .map(|(_, r)| r)
        .filter(|r| !r.is_empty())
}

// ---------------------------------------------------------------------------
// Join: device file + lock entry → Device + links
// ---------------------------------------------------------------------------

/// Joins a parsed device file with its lock entry.
pub(crate) fn join_device(
    path: &Path,
    text: &str,
    locks: &BTreeMap<IndividualAddress, &LockDevice>,
    models: Option<&ProductModels>,
) -> Result<(Device, Vec<Link>), LoadError> {
    let top: DeviceFileTop = toml_io::parse(path, text)?;
    let lock = locks.get(&top.address).copied();
    let doc = toml_io::parse_document(path, text)?;
    let entries = scope_entries(path, text, &doc)?;
    let pinned = top
        .application
        .as_deref()
        .or_else(|| lock.and_then(|l| l.application.as_deref()));
    let resolver = Resolver::with_model(lock, models.zip(pinned).and_then(|(m, a)| m.get(a)));

    // Channels: the lock's, named by the file.
    let mut handle_to_id: BTreeMap<String, String> = BTreeMap::new();
    let mut channels: BTreeMap<String, Channel> = BTreeMap::new();
    let mut module_bases: BTreeMap<String, u32> = BTreeMap::new();
    let mut channel_labels: BTreeMap<String, String> = BTreeMap::new();
    if let Some(lock) = lock {
        for ch in &lock.channels {
            handle_to_id.insert(ch.handle().to_string(), ch.id.clone());
            if let Some(label_ref) = &ch.label_ref {
                channel_labels.insert(ch.id.clone(), label_ref.clone());
            }
            channels.insert(
                ch.id.clone(),
                Channel {
                    name: ch.text.clone().unwrap_or_default(),
                    key: ch.key.clone(),
                    number: ch.number,
                    text: ch.text.clone(),
                },
            );
            if let (Some(base), Some(selector)) = (ch.base, channel_selector(&ch.id)) {
                module_bases.insert(selector.to_string(), base);
            }
        }
        module_bases.extend(lock.module_bases.iter().map(|(k, v)| (k.clone(), *v)));
    }
    let id_of = |handle: &str| -> String {
        handle_to_id
            .get(handle)
            .cloned()
            .unwrap_or_else(|| handle.to_string())
    };
    // The application whose product model normalizes enum labels.
    let app_ref = top
        .application
        .as_deref()
        .or_else(|| lock.and_then(|l| l.application.as_deref()));
    let param_def =
        |key: &str| -> Option<&ParamDef> { models.and_then(|m| m.param_def(app_ref?, key)) };
    let mut spellings: BTreeMap<String, Spelling> = BTreeMap::new();
    // Stores a file value under its in-memory key: an enum label becomes its
    // code when the product model knows it, and the spelling is kept for the
    // save.
    let mut store = |parameters: &mut BTreeMap<String, String>, key: String, value: &str| {
        let code = match param_def(&key).filter(|d| !d.labels.is_empty()) {
            Some(def) => {
                let code = enum_code(&def.labels, value)
                    .map(|c| c.to_string())
                    .unwrap_or_else(|| value.to_string());
                spellings.insert(
                    key.clone(),
                    Spelling {
                        code: code.clone(),
                        text: value.to_string(),
                    },
                );
                code
            }
            None => value.to_string(),
        };
        parameters.insert(key, code);
    };

    let mut parameters: BTreeMap<String, String> = BTreeMap::new();
    for (handle, name, _) in &entries.channels {
        let id = id_of(handle);
        let channel = channels.entry(id.clone()).or_default();
        if let Some(name) = name {
            channel.name = name.clone();
            // A labelled channel's name is its label parameter's value.
            if let Some(label_ref) = channel_labels.get(&id) {
                parameters.insert(label_mem_key(label_ref), name.clone());
            }
        }
    }

    // The values of refs the configuration does not show come from the lock.
    if let Some(lock) = lock {
        for h in &lock.hidden {
            parameters.insert(hidden_mem_key(&h.reference), h.value.clone());
        }
    }

    // Parameters and links. A key the product model resolves (the lock does
    // not list it) gains a lock entry, so the next save records it.
    let mut links: Vec<Link> = Vec::new();
    let mut via_model: Vec<(String, LockedParameter)> = Vec::new();
    for entry in &entries.entries {
        let scope = entry.table.scope();
        match &entry.value {
            EntryValue::Param(value) => {
                let full_key = entry.full_key();
                let key = resolver.param_mem_key(scope, &full_key);
                if resolver.locked_param_ref(scope, &full_key).is_none()
                    && let Some(reference) = resolver.model_param_ref(scope, &full_key)
                {
                    via_model.push((
                        reference,
                        LockedParameter {
                            key: full_key,
                            channel: scope.map(id_of),
                            param: key_to_param_id(&key),
                        },
                    ));
                }
                if ref_of(&key).is_some_and(|r| channel_labels.values().any(|l| l == r)) {
                    // The label is the channel name; an escape-hatch spelling
                    // of it only counts when the channel sets no name.
                    let label_key = ref_of(&key).map(label_mem_key).unwrap_or(key);
                    parameters.entry(label_key).or_insert_with(|| value.clone());
                    continue;
                }
                store(&mut parameters, key, value);
            }
            EntryValue::Object { send, listen, name } => {
                if entry.page.is_some() {
                    continue;
                }
                let Some(object) = resolver.object(scope, &entry.key) else {
                    continue;
                };
                links.push(Link {
                    object,
                    name: name.clone(),
                    send: *send,
                    listen: listen.clone(),
                });
            }
        }
    }
    links.sort_by_key(|l| l.object);

    // Com objects.
    let mut com_objects: BTreeMap<u16, ComObject> = BTreeMap::new();
    if let Some(lock) = lock {
        for o in &lock.objects {
            com_objects.insert(
                o.number,
                ComObject {
                    dpt: o.dpt,
                    size: o.size.clone(),
                    flags: o.flags,
                    reference: o.reference.clone(),
                    channel: o.channel.as_deref().map(id_of),
                    secure: o.secure,
                    key: o.key.clone(),
                    text: o.text.clone(),
                    function: o.function.clone(),
                },
            );
        }
    }

    // Product and security.
    let product = Product {
        manufacturer: lock.and_then(|l| l.manufacturer.clone()),
        manufacturer_ref: lock.and_then(|l| l.manufacturer_ref.clone()),
        order_number: top.product.clone(),
        hardware_ref: lock.and_then(|l| l.hardware_ref.clone()),
        application_ref: top
            .application
            .clone()
            .or_else(|| lock.and_then(|l| l.application.clone())),
        mask: lock.and_then(|l| l.mask.clone()),
    };
    let product = (!product_is_empty(&product)).then_some(product);

    let intent = top.security.unwrap_or_default();
    let security = DeviceSecurity {
        secure_capable: lock.is_some_and(|l| l.secure_capable),
        activated: intent.activated,
        secure_commissioning: intent.secure_commissioning,
        has_fdsk_certificate: lock.is_some_and(|l| l.has_fdsk_certificate),
        sequence_number: lock.and_then(|l| l.sequence_number),
    };
    let security =
        (top.security.is_some() || security != DeviceSecurity::default()).then_some(security);

    // Lock-side bookkeeping, kept only where a save would not rederive it.
    let mut extras = DeviceLock {
        channel_labels,
        spellings,
        ..DeviceLock::default()
    };
    if let Some(lock) = lock {
        if lock.product != top.product {
            extras.product = lock.product.clone();
        }
        if top.application.is_some() {
            extras.application = lock.application.clone();
        }
        let handle_ids = &handle_to_id;
        for p in &lock.parameters {
            let channel = p
                .channel
                .as_deref()
                .map(|h| handle_ids.get(h).cloned().unwrap_or_else(|| h.to_string()));
            let stored_default = p.channel.is_none()
                && ref_of(&p.key) == Some(p.reference.as_str())
                && parameters.contains_key(&p.key)
                && p.param == key_to_param_id(&p.key);
            if !stored_default {
                extras.parameters.insert(
                    p.reference.clone(),
                    LockedParameter {
                        key: p.key.clone(),
                        channel,
                        param: p.param.clone(),
                    },
                );
            }
        }
    }
    extras.parameters.extend(via_model);

    let device = Device {
        address: top.address,
        name: top.name,
        description: top.description,
        location: top.location,
        replaced: top.replaced,
        product,
        channels,
        parameters,
        module_bases,
        com_objects,
        security,
        application_override: top.application,
        lock: extras,
    };
    Ok((device, links))
}

/// Whether every field of a product is unset.
fn product_is_empty(p: &Product) -> bool {
    p.manufacturer.is_none()
        && p.manufacturer_ref.is_none()
        && p.order_number.is_none()
        && p.hardware_ref.is_none()
        && p.application_ref.is_none()
        && p.mask.is_none()
}

// ---------------------------------------------------------------------------
// Split: Device → lock entry + device-file entries
// ---------------------------------------------------------------------------

/// The handle of channel `id` on `device`.
pub(crate) fn handle_of(device: &Device, id: &str) -> String {
    device
        .channels
        .get(id)
        .and_then(|c| c.key.clone())
        .unwrap_or_else(|| id.to_string())
}

/// The device's channels in file order: by the vendor's channel number
/// (channels without one last), then by handle with digit runs compared as
/// numbers, so `ventilausgang-10` follows `ventilausgang-9`. The lock's
/// `channels[]` and the device file's `[channel.*]` tables both use it.
pub(crate) fn ordered_channels(device: &Device) -> Vec<(&String, &Channel)> {
    let mut out: Vec<(&String, &Channel)> = device.channels.iter().collect();
    out.sort_by(|(a_id, a), (b_id, b)| {
        let number = |c: &Channel| c.number.map_or(u64::from(u32::MAX) + 1, u64::from);
        number(a)
            .cmp(&number(b))
            .then_with(|| natural_cmp(&handle_of(device, a_id), &handle_of(device, b_id)))
            .then_with(|| a_id.cmp(b_id))
    });
    out
}

/// Orders two strings with each run of digits compared by value, other
/// characters by code point.
fn natural_cmp(a: &str, b: &str) -> std::cmp::Ordering {
    use std::cmp::Ordering;
    let (a, b) = (a.as_bytes(), b.as_bytes());
    let (mut i, mut j) = (0, 0);
    while i < a.len() && j < b.len() {
        if a[i].is_ascii_digit() && b[j].is_ascii_digit() {
            let (ai, bj) = (i, j);
            while i < a.len() && a[i].is_ascii_digit() {
                i += 1;
            }
            while j < b.len() && b[j].is_ascii_digit() {
                j += 1;
            }
            let (ra, rb) = (
                a[ai..i].iter().skip_while(|d| **d == b'0'),
                b[bj..j].iter().skip_while(|d| **d == b'0'),
            );
            let (ra, rb): (Vec<u8>, Vec<u8>) = (ra.copied().collect(), rb.copied().collect());
            let by_value = ra.len().cmp(&rb.len()).then_with(|| ra.cmp(&rb));
            if by_value != Ordering::Equal {
                return by_value;
            }
        } else {
            if a[i] != b[j] {
                return a[i].cmp(&b[j]);
            }
            i += 1;
            j += 1;
        }
    }
    (a.len() - i).cmp(&(b.len() - j))
}

/// The lock entry for a device, or `None` when it has nothing generated.
pub(crate) fn lock_entry(device: &Device) -> Option<LockDevice> {
    let product = device.product.clone().unwrap_or(Product {
        manufacturer: None,
        manufacturer_ref: None,
        order_number: None,
        hardware_ref: None,
        application_ref: None,
        mask: None,
    });
    let security = device.security.clone().unwrap_or_default();

    let mut channel_selectors: BTreeSet<String> = BTreeSet::new();
    let channels: Vec<LockChannel> = ordered_channels(device)
        .into_iter()
        .map(|(id, ch)| {
            let base = channel_selector(id).and_then(|sel| {
                let base = device.module_bases.get(sel).copied();
                if base.is_some() {
                    channel_selectors.insert(sel.to_string());
                }
                base
            });
            LockChannel {
                key: ch.key.clone(),
                id: id.clone(),
                number: ch.number,
                text: ch.text.clone(),
                label_ref: device.lock.channel_labels.get(id).cloned(),
                base,
            }
        })
        .collect();
    let module_bases: BTreeMap<String, u32> = device
        .module_bases
        .iter()
        .filter(|(k, _)| !channel_selectors.contains(*k))
        .map(|(k, v)| (k.clone(), *v))
        .collect();
    let objects: Vec<LockObject> = device
        .com_objects
        .iter()
        .map(|(number, co)| LockObject {
            number: *number,
            key: co.key.clone(),
            channel: co.channel.as_deref().map(|id| handle_of(device, id)),
            text: co.text.clone(),
            function: co.function.clone(),
            dpt: co.dpt,
            size: co.size.clone(),
            flags: co.flags,
            reference: co.reference.clone(),
            secure: co.secure,
        })
        .collect();

    // One entry per ref: the retained lock entry, else the stored key.
    let mut by_ref: BTreeMap<String, LockParameter> = BTreeMap::new();
    for (reference, p) in &device.lock.parameters {
        by_ref.insert(
            reference.clone(),
            LockParameter {
                key: p.key.clone(),
                channel: p.channel.as_deref().map(|id| handle_of(device, id)),
                reference: reference.clone(),
                param: p.param.clone(),
            },
        );
    }
    let mut hidden: Vec<LockHidden> = Vec::new();
    for (key, value) in &device.parameters {
        let Some(reference) = ref_of(key) else {
            continue;
        };
        if is_hidden_mem_key(key) {
            hidden.push(LockHidden {
                reference: reference.to_string(),
                value: value.clone(),
            });
            continue;
        }
        if is_label_ref(device, reference) {
            continue;
        }
        by_ref
            .entry(reference.to_string())
            .or_insert_with(|| LockParameter {
                key: key.clone(),
                channel: None,
                reference: reference.to_string(),
                param: key_to_param_id(key),
            });
    }
    let mut parameters: Vec<LockParameter> = by_ref.into_values().collect();
    parameters.sort_by(|a, b| {
        (a.channel.as_deref(), a.key.as_str(), a.reference.as_str()).cmp(&(
            b.channel.as_deref(),
            b.key.as_str(),
            b.reference.as_str(),
        ))
    });

    let application = if device.application_override.is_some() {
        device.lock.application.clone()
    } else {
        product.application_ref.clone()
    };
    let entry = LockDevice {
        address: device.address,
        product: device
            .lock
            .product
            .clone()
            .or_else(|| product.order_number.clone()),
        application,
        manufacturer: product.manufacturer.clone(),
        manufacturer_ref: product.manufacturer_ref.clone(),
        hardware_ref: product.hardware_ref.clone(),
        mask: product.mask.clone(),
        secure_capable: security.secure_capable,
        has_fdsk_certificate: security.has_fdsk_certificate,
        sequence_number: security.sequence_number,
        channels,
        module_bases,
        objects,
        parameters,
        hidden,
    };
    let empty = entry.product.is_none()
        && entry.application.is_none()
        && entry.manufacturer.is_none()
        && entry.manufacturer_ref.is_none()
        && entry.hardware_ref.is_none()
        && entry.mask.is_none()
        && !entry.secure_capable
        && !entry.has_fdsk_certificate
        && entry.sequence_number.is_none()
        && entry.channels.is_empty()
        && entry.module_bases.is_empty()
        && entry.objects.is_empty()
        && entry.parameters.is_empty()
        && entry.hidden.is_empty();
    (!empty).then_some(entry)
}

/// Where an entry sits in a device file: its table, page and key.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Placement {
    pub table: TableRef,
    pub page: Option<String>,
    pub key: String,
}

/// Identity of an entry across a save: the in-memory parameter key or the
/// object number (plus an index for an object linked more than once).
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub(crate) enum EntryId {
    Param(String),
    Object(u16, usize),
}

/// The existing file's placements, keyed by what each entry resolves to, so a
/// save keeps the user's spelling (`144` vs `langzeitbetrieb`) and table.
pub(crate) fn existing_placements(
    entries: &DeviceEntries,
    resolver: &Resolver,
) -> BTreeMap<EntryId, Placement> {
    let mut out = BTreeMap::new();
    let mut seen: BTreeMap<u16, usize> = BTreeMap::new();
    for entry in &entries.entries {
        let scope = entry.table.scope();
        let id = match &entry.value {
            EntryValue::Param(_) => {
                EntryId::Param(resolver.param_mem_key(scope, &entry.full_key()))
            }
            EntryValue::Object { .. } => {
                if entry.page.is_some() {
                    continue;
                }
                let Some(n) = resolver.object(scope, &entry.key) else {
                    continue;
                };
                let idx = seen.entry(n).or_insert(0);
                let id = EntryId::Object(n, *idx);
                *idx += 1;
                id
            }
        };
        out.entry(id).or_insert(Placement {
            table: entry.table.clone(),
            page: entry.page.clone(),
            key: entry.key.clone(),
        });
    }
    out
}

/// The entries a device file should hold, with their placement.
pub(crate) fn device_entries(
    device: &Device,
    links: &[Link],
    existing: &BTreeMap<EntryId, Placement>,
    models: Option<&ProductModels>,
) -> Vec<(Placement, EntryValue)> {
    let mut out: Vec<(Placement, EntryValue)> = Vec::new();
    for (key, value) in &device.parameters {
        // A channel's label parameter is written as the channel `name`; a
        // hidden value lives in the lock.
        if is_hidden_mem_key(key) || ref_of(key).is_some_and(|r| is_label_ref(device, r)) {
            continue;
        }
        let placement = existing
            .get(&EntryId::Param(key.clone()))
            .cloned()
            .unwrap_or_else(|| default_param_placement(device, key));
        out.push((
            placement,
            EntryValue::Param(file_value(device, key, value, models)),
        ));
    }
    let mut seen: BTreeMap<u16, usize> = BTreeMap::new();
    let mut used: BTreeSet<(TableRef, String)> = BTreeSet::new();
    let mut sorted: Vec<&Link> = links.iter().collect();
    sorted.sort_by_key(|l| l.object);
    for link in sorted {
        let idx = seen.entry(link.object).or_insert(0);
        let id = EntryId::Object(link.object, *idx);
        *idx += 1;
        let mut placement = existing
            .get(&id)
            .cloned()
            .unwrap_or_else(|| default_object_placement(device, link.object));
        if used.contains(&(placement.table.clone(), placement.key.clone())) {
            // A second link to the same object: spell it by number, or give up
            // (the in-memory model keeps both, the file can hold one).
            let alt = link.object.to_string();
            if alt == placement.key || used.contains(&(placement.table.clone(), alt.clone())) {
                continue;
            }
            placement.key = alt;
        }
        used.insert((placement.table.clone(), placement.key.clone()));
        out.push((
            placement,
            EntryValue::Object {
                send: link.send,
                listen: link.listen.clone(),
                name: link.name.clone(),
            },
        ));
    }
    out
}

/// Whether `reference` is the label parameter of one of the device's channels.
fn is_label_ref(device: &Device, reference: &str) -> bool {
    device
        .lock
        .channel_labels
        .iter()
        .any(|(id, r)| r == reference && device.channels.contains_key(id))
}

/// The value of channel `id`'s label parameter, when it has one.
pub(crate) fn channel_label<'a>(device: &'a Device, id: &str) -> Option<&'a str> {
    let reference = device.lock.channel_labels.get(id)?;
    device
        .parameters
        .iter()
        .find(|(k, _)| ref_of(k) == Some(reference.as_str()))
        .map(|(_, v)| v.as_str())
        .filter(|v| !v.is_empty())
}

/// How the device file spells a parameter value: the recorded spelling while
/// the code is unchanged, else the enum label the product model gives the
/// code, else the value itself.
fn file_value(device: &Device, key: &str, value: &str, models: Option<&ProductModels>) -> String {
    if let Some(s) = device.lock.spellings.get(key)
        && s.code == value
    {
        return s.text.clone();
    }
    let app_ref = device
        .product
        .as_ref()
        .and_then(|p| p.application_ref.as_deref());
    models
        .zip(app_ref)
        .and_then(|(m, app)| m.param_def(app, key))
        .and_then(|def| enum_label(&def.labels, value))
        .map_or_else(|| value.to_string(), str::to_string)
}

/// Where a parameter goes when the file does not place it yet.
fn default_param_placement(device: &Device, key: &str) -> Placement {
    let locked = ref_of(key).and_then(|r| device.lock.parameters.get(r));
    match locked {
        Some(p) => {
            let table = match &p.channel {
                Some(id) => TableRef::Channel(handle_of(device, id)),
                None => TableRef::Parameters,
            };
            match (p.key.contains('@'), p.key.split_once('.')) {
                (false, Some((page, rest))) => Placement {
                    table,
                    page: Some(page.to_string()),
                    key: rest.to_string(),
                },
                _ => Placement {
                    table,
                    page: None,
                    key: p.key.clone(),
                },
            }
        }
        None => Placement {
            table: TableRef::Parameters,
            page: None,
            key: key.to_string(),
        },
    }
}

/// Where an object goes when the file does not place it yet.
fn default_object_placement(device: &Device, number: u16) -> Placement {
    let co = device.com_objects.get(&number);
    let table = match co.and_then(|c| c.channel.as_deref()) {
        Some(id) => TableRef::Channel(handle_of(device, id)),
        None => TableRef::Links,
    };
    let key = co
        .and_then(|c| c.key.clone())
        .unwrap_or_else(|| number.to_string());
    Placement {
        table,
        page: None,
        key,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_slug_folds_umlauts_and_collapses() {
        assert_eq!(slug("Zuordnung Regen"), "zuordnung-regen");
        assert_eq!(slug("Größe / Maß"), "groesse-mass");
        assert_eq!(slug("  --  "), "x");
        assert_eq!(slug("Übersicht (1)"), "uebersicht-1");
    }

    #[test]
    fn test_channel_selector_needs_a_module_instance() {
        assert_eq!(
            channel_selector("MD-1_M-13_MI-1_CH-80"),
            Some("MD-1_M-13_MI-1")
        );
        assert_eq!(channel_selector("CH-1"), None);
    }
}
