//! Rendering derived entities to the Home Assistant `knx:` YAML document.
//!
//! The output is deterministic: entities are sorted by platform, then name,
//! then primary GA, and every optional field is omitted when empty. A header
//! comment marks the file as generated, and a footer comment summarizes any
//! unmapped group addresses so nothing is silently dropped.

use serde::Serialize;

use crate::derive::Derived;
use crate::entities::{BinarySensor, Climate, Cover, Entity, Light, Platform, Sensor, Switch};

/// The header prepended to every generated file.
const HEADER: &str = "# generated by bussard ha-config — do not hand-edit; use ha.yaml overrides\n";

/// The serializable `knx:` document. Each platform is an ordered list; empty
/// lists are omitted so the file only contains what exists.
#[derive(Debug, Serialize, Default)]
struct KnxDocument {
    knx: KnxPlatforms,
}

#[derive(Debug, Serialize, Default)]
struct KnxPlatforms {
    #[serde(skip_serializing_if = "Vec::is_empty")]
    switch: Vec<Switch>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    light: Vec<Light>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    cover: Vec<Cover>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    climate: Vec<Climate>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    sensor: Vec<Sensor>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    binary_sensor: Vec<BinarySensor>,
}

/// Renders derived entities to the final YAML string (header + body + footer).
pub fn render(derived: &Derived) -> Result<String, serde_norway::Error> {
    let mut entities = derived.entities.clone();
    // Deterministic order: platform, then name, then primary GA.
    entities.sort_by(|a, b| {
        a.platform()
            .cmp(&b.platform())
            .then_with(|| a.name().cmp(b.name()))
            .then_with(|| a.primary_ga().raw().cmp(&b.primary_ga().raw()))
    });

    let mut doc = KnxDocument::default();
    for e in entities {
        match e {
            Entity::Switch(x) => doc.knx.switch.push(x),
            Entity::Light(x) => doc.knx.light.push(x),
            Entity::Cover(x) => doc.knx.cover.push(x),
            Entity::Sensor(x) => doc.knx.sensor.push(x),
            Entity::BinarySensor(x) => doc.knx.binary_sensor.push(x),
            Entity::Climate(x) => doc.knx.climate.push(x),
        }
    }

    let body = serde_norway::to_string(&doc)?;

    let mut out = String::new();
    out.push_str(HEADER);
    // If there are no entities at all, `body` is `knx: {}` — still valid.
    out.push_str(&body);
    out.push_str(&footer(derived));
    Ok(out)
}

/// Builds the footer: per-platform counts and the unmapped summary.
fn footer(derived: &Derived) -> String {
    let mut counts = [0usize; 6];
    for e in &derived.entities {
        let idx = match e.platform() {
            Platform::Switch => 0,
            Platform::Light => 1,
            Platform::Cover => 2,
            Platform::Sensor => 3,
            Platform::BinarySensor => 4,
            Platform::Climate => 5,
        };
        counts[idx] += 1;
    }

    let mut s = String::new();
    s.push_str("\n# summary\n");
    s.push_str(&format!(
        "# entities: {} switch, {} light, {} cover, {} climate, {} sensor, {} binary_sensor\n",
        counts[0], counts[1], counts[2], counts[5], counts[3], counts[4]
    ));
    s.push_str(&format!(
        "# group addresses: {}/{} mapped\n",
        derived.mapped_gas, derived.total_gas
    ));

    if derived.unmapped.is_empty() {
        s.push_str("# unmapped: none\n");
    } else {
        // Render as `main.count` pairs, e.g. `1:3 5:2 none:1`, ordered by main.
        let parts: Vec<String> = derived
            .unmapped
            .iter()
            .map(|(main, count)| match main {
                Some(m) => format!("dpt {m}: {count}"),
                None => format!("no-dpt: {count}"),
            })
            .collect();
        let total: usize = derived.unmapped.values().sum();
        s.push_str(&format!(
            "# unmapped: {total} group addresses ({})\n",
            parts.join(", ")
        ));
    }

    // Notes: recognised-but-unwired GAs (e.g. climate forced-mode "Zwang" that
    // the HA KNX schema has no key for). Emitted in sorted order for stability.
    for note in &derived.notes {
        s.push_str(&format!("# note: {note}\n"));
    }
    s
}
