//! TEMPORARY one-off converter: YAML model directory → TOML model directory.
//!
//! `cargo run -p bussard-model --example convert_yaml_model -- <in> [<out>]`
//!
//! Without `<out>` the conversion happens in place and the YAML model files are
//! removed. The result is reloaded and compared with the YAML model.

use std::path::{Path, PathBuf};

use bussard_model::Model;

/// The leading `#` comment block of a file, when it is not an old generated
/// banner.
fn leading_comments(path: &Path) -> Option<String> {
    let text = std::fs::read_to_string(path).ok()?;
    let block: Vec<&str> = text.lines().take_while(|l| l.starts_with('#')).collect();
    if block.is_empty() {
        return None;
    }
    let first = block[0];
    if first.contains("(generated by `bussard import`)")
        || first.starts_with("# bussard.yaml — connection config")
        || first.starts_with("# Device file (generated")
    {
        return None;
    }
    let joined = block.join("\n").replace(".yaml", ".toml");
    Some(format!("{joined}\n\n"))
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let input = PathBuf::from(
        args.first()
            .ok_or("usage: convert_yaml_model <in> [<out>]")?,
    );
    let in_place = args.get(1).is_none();
    let output = args.get(1).map_or_else(|| input.clone(), PathBuf::from);

    let model = bussard_model::legacy_yaml::load(&input)?;
    let texts = model.to_texts()?;
    std::fs::create_dir_all(output.join("devices"))?;

    let had = |name: &str| input.join(name).is_file();
    for (rel, text) in &texts {
        let (keep, source) = match rel.as_str() {
            "bussard.toml" => (had("bussard.yaml"), Some(input.join("bussard.yaml"))),
            "groups.toml" => (
                had("groups.yaml") || !model.groups.groups.is_empty(),
                Some(input.join("groups.yaml")),
            ),
            "bussard.lock" => (
                text.lines()
                    .any(|l| l.starts_with("[[device]]") || l.starts_with("source")),
                None,
            ),
            _ => (true, None),
        };
        if !keep {
            continue;
        }
        let mut body = String::new();
        if let Some(src) = &source
            && let Some(comments) = leading_comments(src)
        {
            body.push_str(&comments);
        }
        body.push_str(text);
        std::fs::write(output.join(rel), body)?;
    }
    // Per-device leading comments (fixtures document themselves this way).
    let devices_in = input.join("devices");
    if devices_in.is_dir() {
        for entry in std::fs::read_dir(&devices_in)? {
            let path = entry?.path();
            if path.extension().and_then(|e| e.to_str()) != Some("yaml") {
                continue;
            }
            let Some(comments) = leading_comments(&path) else {
                continue;
            };
            let text = std::fs::read_to_string(&path)?;
            let Some(addr_line) = text.lines().find(|l| l.starts_with("address:")) else {
                continue;
            };
            let addr = addr_line
                .trim_start_matches("address:")
                .trim()
                .trim_matches(['"', '\'']);
            let target = output.join("devices").join(format!("{addr}.toml"));
            let body = std::fs::read_to_string(&target)?;
            std::fs::write(&target, format!("{comments}{body}"))?;
        }
    }

    if in_place {
        for name in ["bussard.yaml", "groups.yaml", "links.yaml"] {
            let p = input.join(name);
            if p.is_file() {
                std::fs::remove_file(p)?;
            }
        }
        if devices_in.is_dir() {
            for entry in std::fs::read_dir(&devices_in)? {
                let path = entry?.path();
                if path.extension().and_then(|e| e.to_str()) == Some("yaml") {
                    std::fs::remove_file(path)?;
                }
            }
        }
    }
    if std::fs::read_dir(output.join("devices"))?.next().is_none() {
        std::fs::remove_dir(output.join("devices"))?;
    }

    // Verify: the TOML reloads to the same model.
    let back = Model::load(&output)?;
    let mut problems = Vec::new();
    if back.config != model.config {
        problems.push("config".to_string());
    }
    if back.groups != model.groups {
        problems.push("groups".to_string());
    }
    for (addr, links) in &model.links.links {
        let mut want = links.clone();
        want.sort_by_key(|l| l.object);
        let got = back.links.links.get(addr).cloned().unwrap_or_default();
        if got != want && !(want.is_empty() && got.is_empty()) {
            problems.push(format!("links {addr}"));
        }
    }
    for (addr, loaded) in &model.devices {
        match back.devices.get(addr) {
            None => problems.push(format!("device {addr} missing")),
            Some(b) => {
                let mut want = loaded.device.clone();
                if want
                    .security
                    .as_ref()
                    .is_some_and(|s| *s == bussard_model::schema::DeviceSecurity::default())
                {
                    want.security = None;
                }
                if b.device != want {
                    problems.push(format!("device {addr} differs"));
                }
            }
        }
    }
    println!(
        "{} -> {}: {} devices, {} groups{}",
        input.display(),
        output.display(),
        back.devices.len(),
        back.groups.groups.len(),
        if problems.is_empty() {
            String::new()
        } else {
            format!("; MISMATCH: {}", problems.join(", "))
        }
    );
    Ok(())
}
