//! Channel labels and enum labels in device files (docs/model-format.md,
//! "Parameter values" and the lock's `label_ref`): the file's channel `name`
//! is the label parameter's value in memory, an enum label becomes its code
//! when the product model is there, and a save writes both back as the user
//! wrote them.

use std::fs;
use std::path::{Path, PathBuf};

use bussard_model::{IndividualAddress, Model, merge};

type TestResult = Result<(), Box<dyn std::error::Error>>;

fn tmp(tag: &str) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let dir = std::env::temp_dir().join(format!(
        "bussard-labels-{tag}-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)?
            .as_nanos()
    ));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(dir.join("devices"))?;
    Ok(dir)
}

const APP: &str = "M-00FA_A-1";

const LOCK: &str = r#"# This file is @generated by `bussard import` and `bussard adopt`. Do not edit it by hand.
version = 1

[[device]]
address = "1.1.5"
product = "X1"
application = "M-00FA_A-1"
channels = [
  { key = "a-1", id = "CH-1", number = 1, text = "Output A", label_ref = "P-1_R-1" },
]
parameters = [
  { key = "betriebsart", channel = "a-1", ref = "P-2_R-2", param = "P-2" },
]
"#;

const DEVICE: &str = r#"address = "1.1.5"
name = "Aktor"
product = "X1"

[channel.a-1]
name = "Fenster Süd"   # the label
betriebsart = "Jalousie"
"#;

const MODEL: &str = "parameters:
  - id: M-00FA_A-1_P-2
    type: !enum
      values:
        - value: 0
          text: Schalten
        - value: 2
          text: Jalousie
    default: '0'
";

fn model_dir(tag: &str, with_model: bool) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let dir = tmp(tag)?;
    fs::write(dir.join("bussard.lock"), LOCK)?;
    fs::write(dir.join("devices/1.1.5.toml"), DEVICE)?;
    if with_model {
        fs::create_dir_all(dir.join("models"))?;
        fs::write(dir.join(format!("models/{APP}.yaml")), MODEL)?;
    }
    Ok(dir)
}

fn ia() -> Result<IndividualAddress, Box<dyn std::error::Error>> {
    Ok("1.1.5".parse()?)
}

fn read(dir: &Path) -> Result<String, Box<dyn std::error::Error>> {
    Ok(fs::read_to_string(dir.join("devices/1.1.5.toml"))?)
}

#[test]
fn test_load_channel_name_is_the_label_parameter() -> TestResult {
    let dir = model_dir("name", false)?;
    let model = Model::load(&dir)?;
    let device = &model.devices[&ia()?].device;
    assert_eq!(device.channels["CH-1"].name, "Fenster Süd");
    assert_eq!(
        device.parameters.get("label@P-1_R-1").map(String::as_str),
        Some("Fenster Süd")
    );
    // Without a product model the enum label is kept as written.
    assert_eq!(
        device
            .parameters
            .get("betriebsart@P-2_R-2")
            .map(String::as_str),
        Some("Jalousie")
    );
    // The lock keeps the label ref, the parameter list stays without it.
    model.save(&dir)?;
    let lock = fs::read_to_string(dir.join("bussard.lock"))?;
    assert!(lock.contains(r#"label_ref = "P-1_R-1""#), "{lock}");
    assert!(!lock.contains(r#", ref = "P-1_R-1""#), "{lock}");
    assert_eq!(read(&dir)?, DEVICE);
    Ok(())
}

#[test]
fn test_load_enum_label_becomes_its_code_with_a_product_model() -> TestResult {
    let dir = model_dir("enum", true)?;
    let model = Model::load(&dir)?;
    let device = &model.devices[&ia()?].device;
    assert_eq!(
        device
            .parameters
            .get("betriebsart@P-2_R-2")
            .map(String::as_str),
        Some("2")
    );
    // Unchanged, the file keeps the label (and its comment).
    model.save(&dir)?;
    assert_eq!(read(&dir)?, DEVICE);

    // A changed code is written as its label; an unlabelled code as the code.
    let mut model = Model::load(&dir)?;
    let device = &mut model.devices.get_mut(&ia()?).ok_or("device 1.1.5")?.device;
    device
        .parameters
        .insert("betriebsart@P-2_R-2".into(), "0".into());
    model.save(&dir)?;
    assert!(read(&dir)?.contains(r#"betriebsart = "Schalten""#));
    let mut model = Model::load(&dir)?;
    let device = &mut model.devices.get_mut(&ia()?).ok_or("device 1.1.5")?.device;
    device
        .parameters
        .insert("betriebsart@P-2_R-2".into(), "7".into());
    model.save(&dir)?;
    assert!(read(&dir)?.contains(r#"betriebsart = "7""#));
    Ok(())
}

#[test]
fn test_save_renamed_channel_writes_the_new_label() -> TestResult {
    let dir = model_dir("rename", false)?;
    let mut model = Model::load(&dir)?;
    let device = &mut model.devices.get_mut(&ia()?).ok_or("device 1.1.5")?.device;
    device.channels.get_mut("CH-1").ok_or("channel CH-1")?.name = "Tür".into();
    model.save(&dir)?;
    assert!(read(&dir)?.contains(r#"name = "Tür""#));
    let model = Model::load(&dir)?;
    assert_eq!(
        model.devices[&ia()?]
            .device
            .parameters
            .get("label@P-1_R-1")
            .map(String::as_str),
        Some("Tür")
    );
    Ok(())
}

#[test]
fn test_merge_keeps_a_hand_set_label_by_channel_key() -> TestResult {
    let dir = model_dir("merge", false)?;
    let ours = Model::load(&dir)?;
    // A fresh import: same handle, ETS's own label under the channel id.
    let mut theirs = ours.clone();
    let device = &mut theirs.devices.get_mut(&ia()?).ok_or("device 1.1.5")?.device;
    device
        .parameters
        .insert("label@P-1_R-1".into(), "ETS".into());
    device.channels.get_mut("CH-1").ok_or("channel CH-1")?.name = "ETS".into();
    let (merged, report) = merge(&ours, &theirs);
    let device = &merged.devices[&ia()?].device;
    assert_eq!(device.channels["CH-1"].name, "Fenster Süd");
    assert_eq!(
        device.parameters.get("label@P-1_R-1").map(String::as_str),
        Some("Fenster Süd")
    );
    assert!(
        report
            .conflicts
            .iter()
            .any(|c| c.field == "channels.a-1.name")
    );
    Ok(())
}

#[test]
fn test_merge_untouched_channel_name_follows_the_import() -> TestResult {
    let dir = tmp("untouched")?;
    fs::write(dir.join("bussard.lock"), LOCK)?;
    fs::write(
        dir.join("devices/1.1.5.toml"),
        "address = \"1.1.5\"\nname = \"Aktor\"\nproduct = \"X1\"\n",
    )?;
    let ours = Model::load(&dir)?;
    assert_eq!(
        ours.devices[&ia()?].device.channels["CH-1"].name,
        "Output A"
    );
    let mut theirs = ours.clone();
    let device = &mut theirs.devices.get_mut(&ia()?).ok_or("device 1.1.5")?.device;
    device
        .parameters
        .insert("label@P-1_R-1".into(), "ETS".into());
    device.channels.get_mut("CH-1").ok_or("channel CH-1")?.name = "ETS".into();
    let (merged, report) = merge(&ours, &theirs);
    assert_eq!(merged.devices[&ia()?].device.channels["CH-1"].name, "ETS");
    assert!(report.conflicts.is_empty(), "{:?}", report.conflicts);
    Ok(())
}
