//! Lock v2 (issue #228): `[[product]]` entries, the per-device product hash
//! and application id, the refusal of any other lock version, and the E032/E033
//! warnings.

use std::fs;
use std::path::PathBuf;

use bussard_model::schema::ProductOrigin;
use bussard_model::{Model, pin_products, validate_in_dir};

type TestResult = Result<(), Box<dyn std::error::Error>>;

fn tmp(tag: &str) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let dir = std::env::temp_dir().join(format!(
        "bussard-lockv2-{tag}-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)?
            .as_nanos()
    ));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(dir.join("devices"))?;
    fs::write(
        dir.join("devices/1.1.4.toml"),
        "address = \"1.1.4\"\nname = \"Aktor\"\nproduct = \"AKK-0216.03\"\n",
    )?;
    Ok(dir)
}

const HEADER: &str =
    "# This file is @generated by `bussard import` and `bussard adopt`. Do not edit it by hand.\n";

const BARE: &str = r#"version = 2
source = "house.knxproj"

[[device]]
address = "1.1.4"
product = "AKK-0216.03"
application = "M-0083_A-00FA-25-001A"
mask = "07B0"
"#;

const V2: &str = r#"version = 2
source = "house.knxproj"

[[product]]
sha256 = "9f1c00000000000000000000000000000000000000000000000000000000e2e2"
file = "vendor/MDT_AKK-0216.03.knxprod"
filename = "MDT_AKK-0216.03.knxprod"
size = 1184233
origin = { kind = "index", order_number = "AKK-0216.03", url = "https://example.invalid/akk.knxprod" }
applications = ["M-0083_A-00FA-25-001A"]
order_numbers = ["AKK-0216.03", "AKK-0416.03"]

[[device]]
address = "1.1.4"
product = "AKK-0216.03"
application = "M-0083_A-00FA-25-001A"
product_sha256 = "9f1c00000000000000000000000000000000000000000000000000000000e2e2"
application_id = "008300FA25"
mask = "07B0"
application_version = 37
"#;

#[test]
fn test_a_lock_of_another_version_is_refused_with_the_fix() -> TestResult {
    let dir = tmp("v1")?;
    fs::write(
        dir.join("bussard.lock"),
        format!("{HEADER}{BARE}").replace("version = 2", "version = 1"),
    )?;
    let err = Model::load(&dir)
        .err()
        .ok_or("a v1 lock must not load")?
        .to_string();
    assert!(err.contains("version 1 is not supported"), "{err}");
    assert!(err.contains("bussard import"), "{err}");
    fs::remove_dir_all(&dir)?;
    Ok(())
}

#[test]
fn test_save_derives_application_id_and_version_from_the_ref() -> TestResult {
    let dir = tmp("derive")?;
    fs::write(dir.join("bussard.lock"), format!("{HEADER}{BARE}"))?;
    let model = Model::load(&dir)?;
    model.save(&dir)?;
    let lock = fs::read_to_string(dir.join("bussard.lock"))?;
    assert!(lock.contains("application_id = \"008300FA25\"\n"), "{lock}");
    assert!(lock.contains("application_version = 37\n"), "{lock}");
    assert_eq!(Model::load(&dir)?, model);
    fs::remove_dir_all(&dir)?;
    Ok(())
}

#[test]
fn test_v2_lock_round_trips_byte_for_byte() -> TestResult {
    let dir = tmp("v2")?;
    let text = format!("{HEADER}{V2}");
    fs::write(dir.join("bussard.lock"), &text)?;
    let model = Model::load(&dir)?;
    let device = &model.devices[&"1.1.4".parse()?].device;
    let entry = device
        .lock
        .product_entry
        .as_ref()
        .ok_or("the device joins its product entry")?;
    assert_eq!(entry.order_numbers.len(), 2);
    assert!(matches!(entry.origin, ProductOrigin::Index { .. }));
    model.save(&dir)?;
    assert_eq!(fs::read_to_string(dir.join("bussard.lock"))?, text);
    fs::remove_dir_all(&dir)?;
    Ok(())
}

#[test]
fn test_save_keeps_an_unlinked_archive_entry() -> TestResult {
    let dir = tmp("unlinked")?;
    // No device links the product: it was imported on its own.
    let text = format!("{HEADER}{V2}").replace(
        "product_sha256 = \"9f1c00000000000000000000000000000000000000000000000000000000e2e2\"\n",
        "",
    );
    fs::write(dir.join("bussard.lock"), &text)?;
    Model::load(&dir)?.save(&dir)?;
    let lock = fs::read_to_string(dir.join("bussard.lock"))?;
    assert!(lock.contains("[[product]]"), "{lock}");
    fs::remove_dir_all(&dir)?;
    Ok(())
}

#[test]
fn test_e032_dangling_product_link_and_e033_missing_archive() -> TestResult {
    let dir = tmp("diag")?;
    fs::write(dir.join("bussard.lock"), format!("{HEADER}{V2}"))?;
    let codes = |dir: &std::path::Path| -> Result<Vec<String>, Box<dyn std::error::Error>> {
        let model = Model::load(dir)?;
        Ok(validate_in_dir(&model, dir)
            .into_iter()
            .map(|d| d.code.to_string())
            .collect())
    };
    // The archive is not in vendor/: E033 only.
    let found = codes(&dir)?;
    assert!(found.contains(&"E033".to_string()), "{found:?}");
    assert!(!found.contains(&"E032".to_string()), "{found:?}");

    // With the archive present, no product warning.
    fs::create_dir_all(dir.join("vendor"))?;
    fs::write(dir.join("vendor/MDT_AKK-0216.03.knxprod"), b"zip")?;
    let found = codes(&dir)?;
    assert!(
        !found.iter().any(|c| c == "E032" || c == "E033"),
        "{found:?}"
    );

    // A link to a hash with no entry: E032.
    let dangling =
        format!("{HEADER}{V2}").replace("product_sha256 = \"9f1c", "product_sha256 = \"0000");
    fs::write(dir.join("bussard.lock"), dangling)?;
    let found = codes(&dir)?;
    assert!(found.contains(&"E032".to_string()), "{found:?}");
    fs::remove_dir_all(&dir)?;
    Ok(())
}

#[test]
fn test_pin_products_links_the_device() -> TestResult {
    let dir = tmp("pin")?;
    fs::write(dir.join("bussard.lock"), format!("{HEADER}{BARE}"))?;
    let model = Model::load(&dir)?;
    let entry = model
        .devices
        .values()
        .next()
        .map(|_| bussard_model::schema::ProductEntry {
            sha256: "ABCD".to_string(),
            file: Some("vendor/x.knxprod".to_string()),
            filename: Some("x.knxprod".to_string()),
            size: Some(3),
            origin: ProductOrigin::File {
                path: "x.knxprod".to_string(),
            },
            applications: vec!["M-0083_A-00FA-25-001A".to_string()],
            order_numbers: vec!["AKK-0216.03".to_string()],
        })
        .ok_or("a device")?;
    let report = pin_products(&dir, &[entry])?;
    assert!(report.written);
    assert_eq!(report.linked, vec!["1.1.4".parse()?]);
    let model = Model::load(&dir)?;
    let device = &model.devices[&"1.1.4".parse()?].device;
    assert_eq!(device.lock.product_sha256.as_deref(), Some("abcd"));
    assert!(device.lock.product_entry.is_some());
    // Pinning the same entry again changes nothing.
    let again = pin_products(&dir, &[device.lock.product_entry.clone().ok_or("entry")?])?;
    assert!(!again.written);
    fs::remove_dir_all(&dir)?;
    Ok(())
}
