//! The TOML model format (docs/model-format.md): load/save round trips through
//! the lock, format-preserving saves, key resolution, and the E020–E026 rules.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use bussard_model::schema::{ComObject, Device, Link};
use bussard_model::{IndividualAddress, LoadedDevice, Model, Severity, validate, validate_in_dir};

type TestResult = Result<(), Box<dyn std::error::Error>>;

fn tmp(tag: &str) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let dir = std::env::temp_dir().join(format!(
        "bussard-toml-format-{tag}-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)?
            .as_nanos()
    ));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(dir.join("devices"))?;
    Ok(dir)
}

fn write(dir: &Path, rel: &str, text: &str) -> TestResult {
    fs::write(dir.join(rel), text)?;
    Ok(())
}

fn ia(s: &str) -> Result<IndividualAddress, Box<dyn std::error::Error>> {
    Ok(s.parse()?)
}

const GROUPS: &str = r#"project = "Haus"

ranges = [
  { address = "0",   name = "UG" },
]

groups = [
  { address = "0/1/3", name = "Jalousie Auf/Ab",  dpt = "1.008" },
  { address = "0/1/4", name = "Jalousie Position", dpt = "5.001" },
  { address = "0/1/5", name = "Jalousie Stop",     dpt = "1.007" },
  { address = "4/1/2", name = "In Betrieb",        dpt = "1.002" },
]
"#;

const LOCK: &str = r#"# This file is @generated by `bussard import` and `bussard adopt`. Do not edit it by hand.
version = 1
source = "home_test.knxproj"

[[device]]
address = "1.1.47"
product = "230021SU"
application = "M-0004_A-20DE-22-C7D8-O000A"
manufacturer = "Albrecht Jung"
mask = "07B0"
secure_capable = true
sequence_number = 239362131378
channels = [
  { key = "a-1", id = "MD-3_M-18_MI-1_CH-25", number = 1, text = "Relaisausgänge 1/2", base = 2915 },
]
module_bases = { MD-1_M-48_MI-1 = 10476 }
objects = [
  { number = 138, key = "in-betrieb", text = "Allgemein", function = "In Betrieb", dpt = "1.002", flags = "CRT", ref = "O-138_R-13" },
  { number = 144, key = "langzeitbetrieb", channel = "a-1", text = "Jalousie 1", function = "Langzeitbetrieb", dpt = "1.008", flags = "CWTU", ref = "MD-3_M-18_MI-1_O-2-0_R-38" },
  { number = 145, key = "stop", channel = "a-1", dpt = "1.007", flags = "CW" },
  { number = 162, key = "status-position", channel = "a-1", dpt = "5.001", flags = "CRWTU", ref = "MD-3_M-18_MI-1_O-2-18_R-11", secure = true },
]
parameters = [
  { key = "regenalarm", ref = "P-19_R-38", param = "P-19" },
  { key = "betriebsart", channel = "a-1", ref = "MD-3_M-18_MI-1_P-14_R-14", param = "MD-3_P-14" },
  { key = "sollwerte.komfort", channel = "a-1", ref = "MD-3_M-18_MI-1_P-40_R-61", param = "MD-3_P-40" },
]
"#;

const DEVICE: &str = r#"address = "1.1.47"
name = "Jalousieaktor Kind 2"
description = "Fenster"
product = "230021SU"                    # printed on the device

[location]
floor = "DG"
room = "Kind 2 Süd"

[security]
activated = true
secure_commissioning = false

[parameters]
regenalarm = "Ja"

[links]
in-betrieb.send = "4/1/2"

[channel.a-1]
name = "Fenster Süd"                    # my label
betriebsart = 2                         # integer, stored as "2"
langzeitbetrieb.send = "0/1/3"
145 = { listen = ["0/1/5"] }
status-position.listen = ["0/1/4"]

[channel.a-1.sollwerte]
komfort = "21 °C"
"#;

/// A model directory with the keyed example device.
fn keyed_model(tag: &str) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let dir = tmp(tag)?;
    write(&dir, "groups.toml", GROUPS)?;
    write(&dir, "bussard.lock", LOCK)?;
    write(&dir, "devices/1.1.47.toml", DEVICE)?;
    Ok(dir)
}

#[test]
fn test_load_joins_the_device_file_with_its_lock_entry() -> TestResult {
    let dir = keyed_model("join")?;
    let model = Model::load(&dir)?;
    let addr = ia("1.1.47")?;
    let d = &model.devices[&addr].device;
    assert_eq!(d.name, "Jalousieaktor Kind 2");
    let product = d.product.as_ref().ok_or("product")?;
    assert_eq!(product.order_number.as_deref(), Some("230021SU"));
    assert_eq!(
        product.application_ref.as_deref(),
        Some("M-0004_A-20DE-22-C7D8-O000A")
    );
    assert_eq!(product.mask.as_deref(), Some("07B0"));
    let sec = d.security.as_ref().ok_or("security")?;
    assert!(sec.activated && sec.secure_capable);
    assert_eq!(sec.sequence_number, Some(239362131378));

    // Channels keyed by vendor id, with the lock's key and the file's name.
    let ch = &d.channels["MD-3_M-18_MI-1_CH-25"];
    assert_eq!(ch.name, "Fenster Süd");
    assert_eq!(ch.key.as_deref(), Some("a-1"));
    assert_eq!(ch.number, Some(1));
    // Module bases: the channel's `base` plus the channel-less instance.
    assert_eq!(d.module_bases["MD-3_M-18_MI-1"], 2915);
    assert_eq!(d.module_bases["MD-1_M-48_MI-1"], 10476);

    // Com objects carry the channel id, the key, text and function.
    let co = &d.com_objects[&144];
    assert_eq!(co.channel.as_deref(), Some("MD-3_M-18_MI-1_CH-25"));
    assert_eq!(co.key.as_deref(), Some("langzeitbetrieb"));
    assert_eq!(co.function.as_deref(), Some("Langzeitbetrieb"));
    assert!(d.com_objects[&162].secure);

    // Parameters keyed `<slug>@<ref>`, page-qualified and integer values too.
    assert_eq!(d.parameters["regenalarm@P-19_R-38"], "Ja");
    assert_eq!(d.parameters["betriebsart@MD-3_M-18_MI-1_P-14_R-14"], "2");
    assert_eq!(
        d.parameters["sollwerte-komfort@MD-3_M-18_MI-1_P-40_R-61"],
        "21 °C"
    );
    assert_eq!(
        model.groups.imported_from.as_deref(),
        Some("home_test.knxproj")
    );
    fs::remove_dir_all(&dir)?;
    Ok(())
}

#[test]
fn test_keyed_and_numeric_object_keys_resolve_to_the_same_objects() -> TestResult {
    let dir = keyed_model("objects")?;
    let model = Model::load(&dir)?;
    let links = &model.links.links[&ia("1.1.47")?];
    let by_object: BTreeMap<u16, &Link> = links.iter().map(|l| (l.object, l)).collect();
    assert_eq!(by_object.len(), 4, "{links:?}");
    assert_eq!(by_object[&138].send, Some("4/1/2".parse()?)); // `in-betrieb`
    assert_eq!(by_object[&144].send, Some("0/1/3".parse()?)); // `langzeitbetrieb`
    assert_eq!(by_object[&145].listen, vec!["0/1/5".parse()?]); // `145`
    assert_eq!(by_object[&162].listen, vec!["0/1/4".parse()?]);
    fs::remove_dir_all(&dir)?;
    Ok(())
}

#[test]
fn test_keyed_model_validates_clean() -> TestResult {
    let dir = keyed_model("clean")?;
    let model = Model::load(&dir)?;
    let diags = validate_in_dir(&model, &dir);
    let errors: Vec<_> = diags
        .iter()
        .filter(|d| d.severity == Severity::Error)
        .collect();
    assert!(errors.is_empty(), "{errors:#?}");
    fs::remove_dir_all(&dir)?;
    Ok(())
}

#[test]
fn test_unchanged_save_is_byte_identical() -> TestResult {
    let dir = keyed_model("stable")?;
    let model = Model::load(&dir)?;
    model.save(&dir)?;
    assert_eq!(fs::read_to_string(dir.join("devices/1.1.47.toml"))?, DEVICE);
    assert_eq!(fs::read_to_string(dir.join("groups.toml"))?, GROUPS);
    // The lock is regenerated; it reloads to the same model.
    let again = Model::load(&dir)?;
    assert_eq!(again, model);
    fs::remove_dir_all(&dir)?;
    Ok(())
}

#[test]
fn test_save_keeps_comments_and_edits_only_what_changed() -> TestResult {
    let dir = keyed_model("preserve")?;
    let mut model = Model::load(&dir)?;
    let addr = ia("1.1.47")?;
    {
        let d = &mut model.devices.get_mut(&addr).ok_or("device")?.device;
        d.name = "Jalousieaktor Kind 2 Süd".to_string();
        d.parameters.insert(
            "betriebsart@MD-3_M-18_MI-1_P-14_R-14".to_string(),
            "3".to_string(),
        );
    }
    let links = model.links.links.get_mut(&addr).ok_or("links")?;
    for l in links.iter_mut() {
        if l.object == 144 {
            l.send = Some("0/1/4".parse()?);
        }
    }
    links.retain(|l| l.object != 145);
    model
        .groups
        .groups
        .get_mut(&"0/1/5".parse()?)
        .ok_or("group")?
        .name = "Jalousie Halt".to_string();
    model.save(&dir)?;

    let text = fs::read_to_string(dir.join("devices/1.1.47.toml"))?;
    assert!(
        text.contains("name = \"Jalousieaktor Kind 2 Süd\"\n"),
        "{text}"
    );
    assert!(
        text.contains("product = \"230021SU\"                    # printed on the device"),
        "untouched line keeps its comment:\n{text}"
    );
    assert!(
        text.contains("name = \"Fenster Süd\"                    # my label"),
        "{text}"
    );
    assert!(
        text.contains("betriebsart = \"3\"                         # integer, stored as \"2\""),
        "a changed value keeps its trailing comment:\n{text}"
    );
    assert!(text.contains("langzeitbetrieb.send = \"0/1/4\""), "{text}");
    assert!(!text.contains("145 ="), "removed link is gone:\n{text}");
    assert!(
        text.contains("status-position.listen = [\"0/1/4\"]"),
        "{text}"
    );

    let groups = fs::read_to_string(dir.join("groups.toml"))?;
    assert!(groups.contains("name = \"Jalousie Halt\""), "{groups}");
    assert!(
        groups.contains("{ address = \"0/1/3\", name = \"Jalousie Auf/Ab\",  dpt = \"1.008\" },"),
        "untouched rows keep their bytes:\n{groups}"
    );

    let back = Model::load(&dir)?;
    assert_eq!(back, model);
    fs::remove_dir_all(&dir)?;
    Ok(())
}

#[test]
fn test_lock_split_writes_objects_parameters_and_bases() -> TestResult {
    let dir = keyed_model("split")?;
    let model = Model::load(&dir)?;
    let texts = model.to_texts()?;
    let lock = &texts["bussard.lock"];
    assert!(lock.starts_with("# This file is @generated"), "{lock}");
    assert!(lock.contains("source = \"home_test.knxproj\""), "{lock}");
    assert!(
        lock.contains("{ key = \"a-1\", id = \"MD-3_M-18_MI-1_CH-25\", number = 1, text = \"Relaisausgänge 1/2\", base = 2915 }"),
        "{lock}"
    );
    assert!(
        lock.contains("module_bases = { MD-1_M-48_MI-1 = 10476 }"),
        "{lock}"
    );
    assert!(
        lock.contains("{ key = \"sollwerte.komfort\", channel = \"a-1\", ref = \"MD-3_M-18_MI-1_P-40_R-61\", param = \"MD-3_P-40\" }"),
        "{lock}"
    );
    // A fresh render of the device uses the lock's keys and pages.
    let dev = &texts["devices/1.1.47.toml"];
    assert!(dev.contains("[channel.a-1]\n"), "{dev}");
    assert!(
        dev.contains("[channel.a-1.sollwerte]\nkomfort = \"21 °C\""),
        "{dev}"
    );
    assert!(dev.contains("in-betrieb.send = \"4/1/2\""), "{dev}");
    // And the fresh texts load back to the same model.
    assert_eq!(Model::from_texts(&texts)?, model);
    fs::remove_dir_all(&dir)?;
    Ok(())
}

/// A small unkeyed model as an importer produces it (no lock keys).
fn imported_model() -> Result<Model, Box<dyn std::error::Error>> {
    let addr = ia("1.1.4")?;
    let mut com_objects = BTreeMap::new();
    com_objects.insert(
        12u16,
        ComObject {
            dpt: Some("1.008".parse()?),
            flags: "CW".parse()?,
            channel: Some("CH-1".to_string()),
            ..Default::default()
        },
    );
    let mut channels = BTreeMap::new();
    channels.insert(
        "CH-1".to_string(),
        bussard_model::schema::Channel {
            name: "Behang".to_string(),
            ..Default::default()
        },
    );
    let mut parameters = BTreeMap::new();
    parameters.insert(
        "windalarm-1@MD-1_M-3_MI-1_P-3_R-45".to_string(),
        "1".to_string(),
    );
    let device = Device {
        address: addr,
        name: "Jalousieaktor".to_string(),
        description: None,
        location: None,
        replaced: None,
        product: None,
        channels,
        parameters,
        module_bases: BTreeMap::new(),
        com_objects,
        security: None,
        application_override: None,
        lock: Default::default(),
    };
    let mut devices = BTreeMap::new();
    devices.insert(
        addr,
        LoadedDevice {
            device,
            file_stem: addr.to_string(),
        },
    );
    let mut links = BTreeMap::new();
    links.insert(
        addr,
        vec![Link {
            object: 12,
            name: Some("A: Behang Auf/Ab".to_string()),
            send: None,
            listen: vec!["3/0/4".parse()?],
        }],
    );
    Ok(Model {
        config: Default::default(),
        groups: Default::default(),
        links: bussard_model::schema::Links { links },
        devices,
    })
}

#[test]
fn test_unkeyed_model_uses_numbers_and_the_ref_escape_hatch() -> TestResult {
    let model = imported_model()?;
    let texts = model.to_texts()?;
    assert_eq!(
        texts["devices/1.1.4.toml"],
        "address = \"1.1.4\"\nname = \"Jalousieaktor\"\n\n[parameters]\n\
         \"windalarm-1@MD-1_M-3_MI-1_P-3_R-45\" = \"1\"\n\n[channel.CH-1]\n\
         name = \"Behang\"\n12.listen = [\"3/0/4\"]\n12.name = \"A: Behang Auf/Ab\"\n"
    );
    let lock = &texts["bussard.lock"];
    assert!(
        lock.contains("{ number = 12, channel = \"CH-1\", dpt = \"1.008\", flags = \"CW\" }"),
        "{lock}"
    );
    assert!(
        lock.contains("{ key = \"windalarm-1@MD-1_M-3_MI-1_P-3_R-45\", ref = \"MD-1_M-3_MI-1_P-3_R-45\", param = \"MD-1_P-3\" }"),
        "{lock}"
    );
    assert_eq!(Model::from_texts(&texts)?, model);
    Ok(())
}

/// A module-instantiated device whose channel ids sort differently from the
/// handles' natural order: `import` assigns ids in module-instance order but
/// handles `ventilausgang-1`, `-2`, `-3`; the file and lock must read in
/// handle order, not id order.
fn module_instance_model() -> Result<Model, Box<dyn std::error::Error>> {
    let addr = ia("1.1.2")?;
    let mut channels = BTreeMap::new();
    // Ids chosen so BTreeMap (id) order is 1, 3, 2 while the handles' natural
    // order is 1, 2, 3.
    for (id, handle) in [
        ("MD-1_M-1_MI-1_CH-1", "ventilausgang-1"),
        ("MD-1_M-1_MI-3_CH-1", "ventilausgang-3"),
        ("MD-1_M-1_MI-2_CH-1", "ventilausgang-2"),
    ] {
        channels.insert(
            id.to_string(),
            bussard_model::schema::Channel {
                name: handle.to_string(),
                key: Some(handle.to_string()),
                ..Default::default()
            },
        );
    }
    let device = Device {
        address: addr,
        name: "Heizungsaktor".to_string(),
        description: None,
        location: None,
        replaced: None,
        product: None,
        channels,
        parameters: BTreeMap::new(),
        module_bases: BTreeMap::new(),
        com_objects: BTreeMap::new(),
        security: None,
        application_override: None,
        lock: Default::default(),
    };
    let mut devices = BTreeMap::new();
    devices.insert(
        addr,
        LoadedDevice {
            device,
            file_stem: addr.to_string(),
        },
    );
    Ok(Model {
        config: Default::default(),
        groups: Default::default(),
        links: bussard_model::schema::Links {
            links: BTreeMap::new(),
        },
        devices,
    })
}

#[test]
fn test_channels_render_in_handle_order_not_lock_id_order() -> TestResult {
    let model = module_instance_model()?;
    let texts = model.to_texts()?;
    let dev = &texts["devices/1.1.2.toml"];
    let positions: Vec<usize> = [
        "[channel.ventilausgang-1]",
        "[channel.ventilausgang-2]",
        "[channel.ventilausgang-3]",
    ]
    .iter()
    .map(|h| {
        dev.find(h)
            .unwrap_or_else(|| panic!("missing {h} in {dev}"))
    })
    .collect();
    assert!(
        positions.is_sorted(),
        "channel headers not in handle order: {dev}"
    );
    let lock = &texts["bussard.lock"];
    let key_positions: Vec<usize> = [
        "key = \"ventilausgang-1\"",
        "key = \"ventilausgang-2\"",
        "key = \"ventilausgang-3\"",
    ]
    .iter()
    .map(|k| {
        lock.find(k)
            .unwrap_or_else(|| panic!("missing {k} in {lock}"))
    })
    .collect();
    assert!(
        key_positions.is_sorted(),
        "lock channels not in handle order: {lock}"
    );
    assert_eq!(Model::from_texts(&texts)?, model);
    Ok(())
}

#[test]
fn test_parameter_keys_resolve_through_the_lock() -> TestResult {
    let dir = keyed_model("params")?;
    // `regenalarm` at device level; a stray key and the escape hatch too.
    let device = DEVICE.replace(
        "regenalarm = \"Ja\"\n",
        "regenalarm = \"Ja\"\n\"x@P-99_R-1\" = \"5\"\n",
    );
    write(&dir, "devices/1.1.47.toml", &device)?;
    let model = Model::load(&dir)?;
    let d = &model.devices[&ia("1.1.47")?].device;
    assert_eq!(d.parameters["x@P-99_R-1"], "5");
    assert_eq!(d.parameters["regenalarm@P-19_R-38"], "Ja");
    fs::remove_dir_all(&dir)?;
    Ok(())
}

/// `(code, location, severity)` of one diagnostic.
type Found = (String, String, Severity);

fn codes_in(dir: &Path) -> Result<Vec<Found>, Box<dyn std::error::Error>> {
    let model = Model::load(dir)?;
    Ok(validate_in_dir(&model, dir)
        .into_iter()
        .map(|d| (d.code.to_string(), d.location, d.severity))
        .collect())
}

#[test]
fn test_e020_duplicate_object_in_a_device_file() -> TestResult {
    let dir = keyed_model("e020")?;
    let device = DEVICE.replace(
        "langzeitbetrieb.send = \"0/1/3\"\n",
        "langzeitbetrieb.send = \"0/1/3\"\n144.listen = [\"0/1/3\"]\n",
    );
    write(&dir, "devices/1.1.47.toml", &device)?;
    let found = codes_in(&dir)?;
    let e020: Vec<_> = found.iter().filter(|(c, _, _)| c == "E020").collect();
    assert_eq!(e020.len(), 2, "{found:?}");
    assert!(e020[0].1.starts_with("devices/1.1.47.toml:"), "{e020:?}");
    fs::remove_dir_all(&dir)?;
    Ok(())
}

#[test]
fn test_e021_device_without_lock_entry() -> TestResult {
    let dir = keyed_model("e021")?;
    write(&dir, "bussard.lock", "version = 1\n")?;
    let found = codes_in(&dir)?;
    assert!(found.iter().any(|(c, _, _)| c == "E021"), "{found:?}");
    let e021 = found.iter().find(|(c, _, _)| c == "E021").ok_or("E021")?;
    assert_eq!(e021.1, "devices/1.1.47.toml:15:1", "{found:?}");
    fs::remove_dir_all(&dir)?;
    Ok(())
}

#[test]
fn test_e022_product_differs_from_lock() -> TestResult {
    let dir = keyed_model("e022")?;
    write(
        &dir,
        "devices/1.1.47.toml",
        &DEVICE.replace("product = \"230021SU\"", "product = \"230022SU\""),
    )?;
    let found = codes_in(&dir)?;
    let e022 = found.iter().find(|(c, _, _)| c == "E022").ok_or("E022")?;
    assert_eq!(e022.1, "devices/1.1.47.toml:4:1");
    // A save by any other command keeps the lock's product, so it stays stale.
    let model = Model::load(&dir)?;
    model.save(&dir)?;
    assert!(codes_in(&dir)?.iter().any(|(c, _, _)| c == "E022"));
    fs::remove_dir_all(&dir)?;
    Ok(())
}

#[test]
fn test_e023_unknown_keys_list_the_channel_keys() -> TestResult {
    let dir = keyed_model("e023")?;
    let device = DEVICE
        .replace("betriebsart = 2", "betriebsartt = 2")
        .replace("status-position.listen", "status-postion.listen");
    write(&dir, "devices/1.1.47.toml", &device)?;
    let model = Model::load(&dir)?;
    let diags = validate_in_dir(&model, &dir);
    let e023: Vec<_> = diags.iter().filter(|d| d.code == "E023").collect();
    assert_eq!(e023.len(), 2, "{diags:#?}");
    assert!(
        e023.iter().any(|d| d.message.contains("`betriebsartt`")
            && d.message.contains("`langzeitbetrieb`")
            && d.message.contains("`betriebsart`")),
        "{e023:#?}"
    );
    // The unknown object entry survives a save for the user to fix.
    model.save(&dir)?;
    let text = fs::read_to_string(dir.join("devices/1.1.47.toml"))?;
    assert!(text.contains("status-postion.listen"), "{text}");
    fs::remove_dir_all(&dir)?;
    Ok(())
}

#[test]
fn test_e024_and_e025_flag_dpt_and_direction_mismatches() -> TestResult {
    let dir = keyed_model("e024")?;
    // 145 (1.007, flags CW) sends on the 5.001 position GA.
    let device = DEVICE.replace(
        "145 = { listen = [\"0/1/5\"] }",
        "145 = { send = \"0/1/4\" }",
    );
    write(&dir, "devices/1.1.47.toml", &device)?;
    let model = Model::load(&dir)?;
    let codes: Vec<&str> = validate(&model).iter().map(|d| d.code).collect();
    assert!(codes.contains(&"E024"), "{codes:?}");
    assert!(codes.contains(&"E025"), "{codes:?}");
    fs::remove_dir_all(&dir)?;
    Ok(())
}

#[test]
fn test_e026_parameters_without_a_product_model_warn() -> TestResult {
    let dir = keyed_model("e026")?;
    let found = codes_in(&dir)?;
    let e026 = found.iter().find(|(c, _, _)| c == "E026").ok_or("E026")?;
    assert_eq!(e026.2, Severity::Warning);
    fs::remove_dir_all(&dir)?;
    Ok(())
}

#[test]
fn test_undeclared_ga_is_a_warning() -> TestResult {
    let dir = keyed_model("undeclared")?;
    let device = DEVICE.replace("in-betrieb.send = \"4/1/2\"", "in-betrieb.send = \"4/1/9\"");
    write(&dir, "devices/1.1.47.toml", &device)?;
    let found = codes_in(&dir)?;
    let e001 = found.iter().find(|(c, _, _)| c == "E001").ok_or("E001")?;
    assert_eq!(e001.2, Severity::Warning);
    fs::remove_dir_all(&dir)?;
    Ok(())
}

/// The device file holds only security intent (`activated`,
/// `secure_commissioning`); what the device or the project generated
/// (`secure_capable`, `has_fdsk_certificate`, `sequence_number`) lives in the
/// lock and never reaches the user's file, not even after a save.
#[test]
fn test_device_generated_security_facts_stay_in_the_lock() -> TestResult {
    let dir = keyed_model("security-lock-only")?;
    let mut model = Model::load(&dir)?;
    let addr = ia("1.1.47")?;
    {
        let d = &mut model.devices.get_mut(&addr).ok_or("device")?.device;
        let sec = d.security.as_mut().ok_or("security")?;
        sec.has_fdsk_certificate = true;
        sec.sequence_number = Some(42);
        // Force a rewrite of the device file.
        d.name = "Jalousieaktor Kind 2 Nord".to_string();
    }
    model.save(&dir)?;
    let device = fs::read_to_string(dir.join("devices/1.1.47.toml"))?;
    for generated in ["secure_capable", "has_fdsk_certificate", "sequence_number"] {
        assert!(
            !device.contains(generated),
            "{generated} in the device file:\n{device}"
        );
    }
    assert!(device.contains("activated = true"), "{device}");
    let lock = fs::read_to_string(dir.join("bussard.lock"))?;
    assert!(lock.contains("secure_capable = true"), "{lock}");
    assert!(lock.contains("has_fdsk_certificate = true"), "{lock}");
    assert!(lock.contains("sequence_number = 42"), "{lock}");

    // A device file that states a generated fact is refused: it is not the
    // user's to set.
    let edited = DEVICE.replace(
        "secure_commissioning = false",
        "secure_commissioning = false\nsecure_capable = true",
    );
    write(&dir, "devices/1.1.47.toml", &edited)?;
    assert!(Model::load(&dir).is_err());
    fs::remove_dir_all(&dir)?;
    Ok(())
}

/// The values ETS stores for refs the configuration does not show live in the
/// lock's `hidden[]`: they load into the parameter map next to the shown
/// values (so a flash writes them), never reach the device file, and come
/// back out of the lock unchanged.
#[test]
fn test_hidden_values_round_trip_through_the_lock_only() -> TestResult {
    let dir = tmp("hidden")?;
    write(&dir, "groups.toml", GROUPS)?;
    let lock = format!(
        "{LOCK}hidden = [\n  {{ ref = \"MD-3_M-18_MI-1_P-103_R-160\", value = \"1\" }},\n  \
         {{ ref = \"P-19_R-39\", value = \"0\" }},\n]\n"
    );
    write(&dir, "bussard.lock", &lock)?;
    write(&dir, "devices/1.1.47.toml", DEVICE)?;
    let model = Model::load(&dir)?;
    let d = &model.devices[&ia("1.1.47")?].device;
    assert_eq!(
        d.parameters
            .get("hidden@MD-3_M-18_MI-1_P-103_R-160")
            .map(String::as_str),
        Some("1")
    );
    assert_eq!(
        d.parameters.get("hidden@P-19_R-39").map(String::as_str),
        Some("0")
    );
    let hidden = d
        .parameters
        .keys()
        .filter(|k| bussard_model::is_hidden_mem_key(k))
        .count();
    assert_eq!(hidden, 2);
    assert!(d.parameters.len() > 2, "{:?}", d.parameters);

    // Split again: the file shows only what ETS shows, the lock keeps the rest.
    let texts = model.to_texts()?;
    let dev = &texts["devices/1.1.47.toml"];
    assert!(
        !dev.contains("hidden") && !dev.contains("R-160") && !dev.contains("R-39"),
        "{dev}"
    );
    let lock = &texts["bussard.lock"];
    assert!(
        lock.contains(
            "hidden = [\n  { ref = \"MD-3_M-18_MI-1_P-103_R-160\", value = \"1\" },\n  \
             { ref = \"P-19_R-39\", value = \"0\" },\n]\n"
        ),
        "{lock}"
    );
    assert_eq!(Model::from_texts(&texts)?, model);

    // A format-preserving save leaves the device file untouched.
    model.save(&dir)?;
    assert_eq!(fs::read_to_string(dir.join("devices/1.1.47.toml"))?, DEVICE);
    assert_eq!(Model::load(&dir)?, model);
    fs::remove_dir_all(&dir)?;
    Ok(())
}
